### ISSUE TITLE
Garbage collector article makes mixed use of `gc_ref` and `gc_refs`

### ISSUE THREAD

**Issue by zikcheng** [python/devguide#1026]
In this article https://github.com/python/devguide/blob/main/internals/garbage-collector.rst, when describing how garbage collector works, it uses both `gc_ref` and `gc_refs`. And the picture uses `gc_ref`. And in CPython source code the variable name is `gc_refs`. Should we use only `gc_ref` and redraw the picture?

**Comment by pablogsal** [comment]
Thanks for opening this issue @zikcheng!

I think I am going to rename `gc_refs` to `gc_ref` in the text (even if the implementation uses `gc_refs`) as I prefer not to redraw the pictures and it really doesn't matter if it doesn't match exactly the current implementation as long as is consistent in the text.

Thanks for the catch!
