### ISSUE TITLE
Should an issue be created first, before the Pull Request?

### ISSUE THREAD

**Issue by Mariatta** [python/devguide#104]
In the Quick Start section of the Dev Guide:
```
5. Make a pull request.

6. Create an issue on the issue tracker if one does not already exist.
```

Just wondering if it might be better if an issue be created first (in bpo) before the pull request?
This way Pull Request can be created with `bpo-NNNN:` in the PR title as well as the commit message.

**Comment by ezio-melotti** [comment]
Maybe we could even leave this out from the quick start, in most of the cases there is already an issue, or one is created beforehand in order to discuss the details of the fix.  Eventually we might also automate the issue creation for PR that don't refer to any existing issue.

**Comment by matrixise** [comment]
Or just add "If there is no issue, create it before the PR and note the PR with "bpo-ISSUENUMBER Description".

**Comment by berkerpeksag** [comment]
We should also mention that there is no need create an issue for trivial changes like typo fixes.
