### ISSUE TITLE
Victor Stinner’s guide has broken link in documentation

### ISSUE THREAD

**Issue by Dev-satish** [python/devguide#1044]
# Description:
while going through the python's developer guide for [window's installation and setup](https://devguide.python.org/getting-started/setup-building/#windows) I encountered a broken link for [Victor Stinner's guide](https://cpython-core-tutorial.readthedocs.io/en/latest/build_cpython_windows.html) and even the link on the error page is broken for [_Back to the front page of cpython-core-tutorial.readthedocs.io_](https://cpython-core-tutorial.readthedocs.io/) 

## Expected behavior:
The hyperlink should have taken you to _Victor Stinner's Guide_ (which I believe is this: https://vstinner.readthedocs.io/) and other broken links in that document should be fixed

## Screenshots
![s1](https://user-images.githubusercontent.com/108570204/217528972-fe087e4c-deda-4548-9ea6-38d3ca9c19a2.png)
![s2](https://user-images.githubusercontent.com/108570204/217529051-e12d2bf5-a370-4dbd-adb5-5ffc8b8fb2a2.png)
![s3](https://user-images.githubusercontent.com/108570204/217529067-741b0247-ffe1-44e7-ad8d-3992388cf146.png)

**Comment by arhadthedev** [comment]
@vstinner

**Comment by erlend-aasland** [comment]
There's no need to ping Victor; just fix the link.

**Comment by Dev-satish** [comment]
hey there i wanted to ask if i could work on fixing these links 
@arhadthedev @erlend-aasland

**Comment by arhadthedev** [comment]
@Dev-satish Yes, sure. The only thing you need is to follow the contributor's manual at https://devguide.python.org/ where conventions and processes are described.

@erlend-aasland I was unsure whether https://vstinner.readthedocs.io/ is the guide or an unrelated blog.

**Comment by arhadthedev** [comment]
No need for an assignment, it's an open project. As for guidance... I forgot that this is just a documentation repo. So just create a PR, nothing special.

**Comment by hugovk** [comment]
https://vstinner.readthedocs.io is another site.

The broken link is to:

* https://cpython-core-tutorial.readthedocs.io/en/latest/build_cpython_windows.html

Here's an archived version:

* https://web.archive.org/web/20220907075854/https://cpython-core-tutorial.readthedocs.io/en/latest/build_cpython_windows.html

The site was "Tutorial to contribute to the CPython project":

* https://web.archive.org/web/20221207082044/https://cpython-core-tutorial.readthedocs.io/en/latest/

And the repo was archived last month:

* https://github.com/vstinner/cpython_core_tutorial

The short term fix is to link to the archived version, but it would be better to find another page, or incorporate the necessary information directly into the devguide.

**Comment by hugovk** [comment]
Looking at the output of `make linkcheck`, there's two other broken links we can fix.

---

`(core-developers/become-core-developer: line   46) broken    https://github.com/python/voters - 404 Client Error: Not Found for url: https://github.com/python/voters`

This is a private repo so we should skip checking it.

We already have an entry in `conf.py` to ignore `https://github.com/python/voters/`, but it has a trailing slash. Let's remove the slash so it continues to ignore it.

---

`(advanced-tools/gdb: line   23) broken    https://sourceware.org/gdb/current/onlinedocs/gdb/Python.html#Python - 404 Client Error: Not Found for url: https://sourceware.org/gdb/current/onlinedocs/gdb/Python.html`

Looking at the [archive](https://web.archive.org/web/20221129045405/http://www.sourceware.org/gdb/current/onlinedocs/gdb/Python.html), this is now at https://sourceware.org/gdb/onlinedocs/gdb/Python.html 

---

Please could you update these as well?

**Comment by arhadthedev** [comment]
> [..] and even the link on the error page is broken for [Back to the front page of cpython-core-tutorial.readthedocs.io](https://cpython-core-tutorial.readthedocs.io/)

However, I believe this will be fixed after gh-1042 lands.

**Comment by hugovk** [comment]
Nope, that's a link on https://cpython-core-tutorial.readthedocs.io/ ... back to the front page of https://cpython-core-tutorial.readthedocs.io/ :)

gh-1042 is for links on https://devguide.python.org/ (btw I've just merged this).

**Comment by CAM-Gerlach** [comment]
> The short term fix is to link to the archived version, but it would be better to find another page, or incorporate the necessary information directly into the devguide.

See https://github.com/python/devguide/pull/989#discussion_r1029598112 for some further discussion of that

**Comment by Dev-satish** [comment]
if i make changes in the rst file and send a PR that should solve the issue right (I am a beginner)

**Comment by hugovk** [comment]
Yes, that's right! Don't hesitate to ask if you've any questions :)

**Comment by Dev-satish** [comment]
> https://vstinner.readthedocs.io is another site.
> 
> The broken link is to:
> 
> * https://cpython-core-tutorial.readthedocs.io/en/latest/build_cpython_windows.html
> 
> Here's an archived version:
> 
> * https://web.archive.org/web/20220907075854/https://cpython-core-tutorial.readthedocs.io/en/latest/build_cpython_windows.html
> 
> The site was "Tutorial to contribute to the CPython project":
> 
> * https://web.archive.org/web/20221207082044/https://cpython-core-tutorial.readthedocs.io/en/latest/
> 
> And the repo was archived last month:
> 
> * https://github.com/vstinner/cpython_core_tutorial
> 
> The short term fix is to link to the archived version, but it would be better to find another page, or incorporate the necessary information directly into the devguide.

it would be great if you can tell me, which link should i add in the place of that broken link of Victor Stinner’s guide ?  

shall i add this  https://web.archive.org/web/20220907075854/https://cpython-core-tutorial.readthedocs.io/en/latest/build_cpython_windows.html  or https://github.com/vstinner/cpython_core_tutorial ?

**Comment by hugovk** [comment]
Let's go with https://web.archive.org/web/20220907075854/https://cpython-core-tutorial.readthedocs.io/en/latest/build_cpython_windows.html for a quick fix.

**Comment by Dev-satish** [comment]
I have created a pull request and i am getting this error "Thank you for authorizing our application, but the CLA must be signed by the users who contributed to the PR. Authors emails are: dev_satish@satish.localdomain.", 
what should i do ?

**Comment by hugovk** [comment]
What happens when you click the button to sign?

**Comment by arhadthedev** [comment]
You need to commit using one of e-mails you specified in GitHub profile settings (you can add as much as you want there).

Move your `fixingvictorstinnersguidelink` branch back to `main`, make this commit again with the correct email, and force-push the branch.

**Comment by hugovk** [comment]
> I've run the following before giving a pull request `dev_satish@Satish:~$ git config user.email` `7506satish@gmail.com`

You'll need to do that before creating the commit.

I can see the current commit was made with `dev_satish@Satish.localdomain` by looking at https://github.com/python/devguide/pull/1048.patch

One way to fix it:

```sh
git reset --soft HEAD~1  # This resets the last commit
git commit -m "[PATCH] #1044 fixing victor stinner's guide link"  # Commit again
git push --force  # Forces the new commit to be pushed, which updates the PR
```

**Comment by arhadthedev** [comment]
Also, the status will update not instantly but up to 24 hours.

**Comment by Dev-satish** [comment]
ok! got it! thank you so much for explaining it to me

**Comment by Dev-satish** [comment]
@hugovk @arhadthedev Hi, since the CLA issue isn't getting resolved by a lot of methods I tired so I am deleting the current PR and opening a new one. My apologies.

**Comment by hugovk** [comment]
Thank you @Dev-satish, I've merged https://github.com/python/devguide/pull/1050!

Would you also like to fix the broken links in https://github.com/python/devguide/issues/1044#issuecomment-1422607037?

That is:

1) in `conf.py`: remove the slash at the end of `'https://github.com/python/voters/',` 
2) in `advanced-tools/gdb.rst`: replace `https://sourceware.org/gdb/current/onlinedocs/gdb/Python.html` with `https://sourceware.org/gdb/onlinedocs/gdb/Python.html`

These could be in the same PR.

**Comment by vstinner** [comment]
Right, I archived https://github.com/vstinner/cpython_core_tutorial. Well, if the devguide is incomplete, you may copy the information from my archived documentation into the devguide, rather than using archive.org links.

* https://github.com/vstinner/cpython_core_tutorial/blob/main/build_cpython_linux.rst
* https://github.com/vstinner/cpython_core_tutorial/blob/main/build_cpython_macos.rst
* https://github.com/vstinner/cpython_core_tutorial/blob/main/build_cpython_windows.rst

I wrote these documents since I was unable to find how to build Python from the devguide which is "too complete". Shorter and more concrete instructions might help newcomers ;-)

**Comment by CAM-Gerlach** [comment]
Thanks! I opened this as a followup issue, #1074. I did actually make a number of improvements and simplifications to the Windows section in PR #989 , many directly inspired by your guide, and in another PR we made some similar improvements to the Mac section. However, it seems there is still more to do, and perhaps a short summary snippet could be provided as well.
