### ISSUE TITLE
Specify timezone when creating NEWS entries manually?

### ISSUE THREAD

**Issue by Eclips4** [python/devguide#1045]
> <datetime> is today’s date joined with a hyphen (-) to the current time, in the YYYY-MM-DD-hh-mm-ss format (e.g. 2017-05-27-16-46-23).

Section `Updating NEWS and What’s New in Python` in `core-developers/commiting/` say's nothing about timezone. Should we specify information about timezone?
Something like that "... is today’s date joined with a hyphen (-) to the current time by UTC format ..."

**Comment by CAM-Gerlach** [comment]
@Eclips4 The time zone doesn't really matter, as far as I'm aware; it's only used for uniqueness and sorting the blurbs, as far as I can tell, and `blurb` just uses the local time zone of whatever user is writing the NEWS entry so its effectively arbitrary. The format is specified there:

> <datetime> is today’s date joined with a hyphen (-) to the current time, in the YYYY-MM-DD-hh-mm-ss format (e.g. 2017-05-27-16-46-23).

However, if it is a point of significant confusion, perhaps it could be revised to

> <datetime> is today’s date joined with a hyphen (-) to your current local time, in the YYYY-MM-DD-hh-mm-ss format (e.g. 2017-05-27-16-46-23).

**Comment by Eclips4** [comment]
Thanks for your answer!
It's really confused me. I'll send the PR
