### ISSUE TITLE
GDB section is not up to date

### ISSUE THREAD

**Issue by ogrisel** [python/devguide#1056]
The section about configuring gdb to enable python-aware debugging does not seem up to date:

- https://devguide.python.org/advanced-tools/gdb

In particular it assumes that there exists a file named `python-gdb.py` at the root of a checkout of the CPython source tree and that it is therefore enough to add `add-auto-load-safe-path /path/to/checkout` to the `$HOME/.gdbinit` file to get the `py-bt` command working for instance.

However, I cannot locate the `python-gdb.py` file in the cpython repo. Instead I found:

- https://github.com/python/cpython/blob/main/Tools/gdb/libpython.py

so I assume, that the correct way to enable the python specific commands is to do:

```
gdb python --args my_python_script.py
source /path/to/cpython/Tools/gdb/libpython.py
```

or maybe, the `Tools/gdb/libpython.py` file should be symlinked as `python-gdb.py` somewhere and then add the `add-auto-load-safe-path` directive pointing to the parent folder of the symlink for gdb to automatically load it (but apparently this does not seem to work).

I am not familiar enough with gdb to know how to fix the documentation.

**Comment by CAM-Gerlach** [comment]
Thanks for the detailed report, and sorry for the trouble! I've pinged our GDB subject matter experts to take a look at this and recommend what to do about it.

**Comment by ogrisel** [comment]
Note: maybe turning the filename(s) into links would make it possible to automatically detect such problems in the future (as done in #1003).

**Comment by markshannon** [comment]
When building CPython with `make`, python-gdb.py will be installed for you.
If you are debugging a CPython that you haven't built yourself, just copy /Tools/gdb/libpython.py to  python-gdb.py.

**Comment by carljm** [comment]
Specifically, see the `gdbhooks` target in the Makefile, which is a dependency of the default target.

**Comment by CAM-Gerlach** [comment]
I see the docs do currently imply this:

> When CPython is built you will notice a python-gdb.py file in the root directory of your checkout.

Perhaps it could use a brief note or a more explicit mention, though, if users are getting confused here?

**Comment by carljm** [comment]
> Perhaps it could use a brief note or a more explicit mention, though, if users are getting confused here?

I wouldn't stand in the way, but personally I'd wait for n>1 before spending time on that.
