### ISSUE TITLE
macOS build instructions depend on Homebrew specific configuration

### ISSUE THREAD

**Issue by erlend-aasland** [python/devguide#1059]
Comment by Ned in PR #1058:

> I like this approach but, as I've just discovered, Homebrew has just changed the game again by making their tcl-tk formula no longer "keg-only". As noted [here](https://github.com/python/cpython/pull/102186#issuecomment-1445464817), we should re-think this a bit in that light. I'll have some more thoughts on it soon.

_Originally posted by @ned-deily in https://github.com/python/devguide/issues/1058#issuecomment-1445479500_

**Comment by erlend-aasland** [comment]
Blocks #1058

**Comment by abdnafees** [comment]
I can work on this one, I am on macOS.

**Comment by CAM-Gerlach** [comment]
Seems like this is pending additional analysis by @ned-deily , so I'm not sure there's anything to be done at the moment, @abdnafees ?

**Comment by erlend-aasland** [comment]
FTR, since it is not explicitly noted already:

The devguide currently manipulates `PKG_CONFIG_PATH`, and then incorrectly assumes it is set in the subshells on the same line. Condense example, as shown by Ned in a related issue or PR (I don't have the link at hand):

```console
$ PKG_CONFIG_PATH="$(brew --prefix tcl-tk)/lib/pkgconfig" echo $(pkg-config --libs tcl tk)
Package tcl was not found in the pkg-config search path.
Perhaps you should add the directory containing `tcl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'tcl' found
Package tk was not found in the pkg-config search path.
Perhaps you should add the directory containing `tk.pc'
to the PKG_CONFIG_PATH environment variable
No package 'tk' found
```

This is not an issue _right now_, since Homebrew changed their behaviour (also noted by Ned). But it _may_ be an issue if Homebrew changes their behaviour again.

As a first step, we could inline the `PGK_CONFI_PATH` manipulations into the subshells. Verbose, yes, but it will be correct and safe.

**Comment by abdnafees** [comment]
Everything went over my head.

**Comment by CAM-Gerlach** [comment]
@abdnafees Given that and considering that the experts @ned-deily and @erlend-aasland have been taking care of this one, you might want to consider helping with a more appropriate issue for a new contributor—there are [plenty with a Help Wanted label](https://github.com/python/devguide/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22), as well as others on the main CPython repo and others.

**Comment by abdnafees** [comment]
@CAM-Gerlach Thank you so much. I will check them out.

**Comment by erlend-aasland** [comment]
As per the current recommendation, there's nothing to be done here anymore.
