### ISSUE TITLE
Pip displays "search" in help output, but it is no longer supported

### ISSUE THREAD

**Issue by yxyang93** [python/devguide#1071]
**Describe the bug**
I have encountered an issue with pip where the "search" parameter is still being shown when running pip -h, but using pip search results in an error, as the functionality is not supported anymore. The help output should be updated to remove the "search" parameter since it is no longer supported.

**Steps to reproduce**

1. Run pip -h or pip --help. The "search" parameter is listed among the available commands.
2. Try running pip search <package-name>.

**Expected behavior**
The help output should not display the "search" parameter since it is no longer supported.

**Actual behavior**
When using pip search <package-name>, the search functionality does not work, and an error message indicates that it is no longer supported. However, the "search" parameter is still shown in the help output.

**Version info**
Python: 3.11.2
pip: 23.0.1

**Comment by hugovk** [comment]
This is the repo for the documentation to help you develop on CPython. This belongs on the pip issue tracker at https://github.com/pypa/pip/issues/

But see more info about the pip search command here: https://github.com/pypa/pip/issues/5216 and specifically https://github.com/pypa/pip/issues/5216#issuecomment-1426803024.
