### ISSUE TITLE
Document the use of GitHub automerge

### ISSUE THREAD

**Issue by Mariatta** [python/devguide#1079]
**Describe the enhancement or feature you'd like**
We will begin using GitHub's automerge instead of miss-islington's automerge.
We need this to be documented on Devguide.

**Additional context**
See details and checklist here https://github.com/python/core-workflow/issues/498#issuecomment-1502516107

A PR to miss-islington has been made to remove the automerge functionality.
Once we have the doc prepared, we can continue with the process.

**Comment by NishanthMuruganantham** [comment]
@hugovk @Mariatta  I like to get my hands on it. Can you give me some more insights on this?

**Comment by Mariatta** [comment]
Here are the changes needed:

- Create a new section in https://devguide.python.org/core-developers/committing/ about automerging.

- in that new section, describe how it works, what it is (perhaps link to GitHub's own doc)

- in the same section, describe how to trigger it.

It seems like you're a first time contributor here. You may want to read up on how to contribute to the devguide here: https://devguide.python.org/documentation/devguide/

**Comment by methane** [comment]
I think current default commit message is "pull request title and commit details".

<img width="879" alt="image" src="https://user-images.githubusercontent.com/199592/233392171-a7879a23-c9e4-4405-8f86-272c81bf790a.png">

Before using automerge, I think we should change it to "pull request title and descriptions".

<img width="574" alt="image" src="https://user-images.githubusercontent.com/199592/233392009-86544f5a-a5f6-44d4-af14-0d649210a13f.png">

**Comment by methane** [comment]
I filed a new issue to core-workflow#501 about default commit message.

**Comment by hugovk** [comment]
@NishanthMuruganantham Hi, have you had a chance to look at this yet?
