### ISSUE TITLE
Remove the "automerge" label

### ISSUE THREAD

**Issue by Mariatta** [python/devguide#1080]
> Note: This repo is for the Python devguide. If you are requesting an
enhancement for the Python language or CPython interpreter,
then the CPython issue tracker is better
suited for this report: https://github.com/python/cpython/issues

**Describe the enhancement or feature you'd like**
Prepare a PR for removing the "automerge" label from the Triage > Labels page  https://devguide.python.org/triage/labels/

**Additional context**
After #1079 is done, and after the label has actually been removed, we should update the doc. The PR for removing it from the doc can be prepared in advance.

**Comment by gantanikhilraj** [comment]
Can I work on this @Mariatta, Please do assign it to me.

**Comment by Mariatta** [comment]
You can stay and go ahead to create a pr

**Comment by arhadthedev** [comment]
Resolved by gh-1082.
