### ISSUE TITLE
Document `issue`, `gh-issue` and `source` roles

### ISSUE THREAD

**Issue by hugovk** [python/devguide#1091]
**Describe the enhancement or feature you'd like**

We define three Sphinx roles in `pyspecific.py`: `issue`, `gh-issue` and `source`.

https://github.com/python/cpython/blob/a679c3d58d10aafd9ac9355fdd16151607e37d65/Doc/tools/extensions/pyspecific.py#L54-L92

* `issue` is for issues on the old https://bugs.python.org, and so won't be used much anymore, but still exists in lots of old docs
* `gh-issue` is for new issues on GitHub
* `source` is for linking to source files on GitHub

Let's document them somewhere on https://devguide.python.org/documentation/markup/#roles

**Describe alternatives you've considered**

Don't document them = status quo.

Remove them = make the docs worse.

**Comment by zware** [comment]
Confusingly, `gh-issue` does not exist as a role.  It's `gh` instead: https://github.com/python/cpython/blob/a679c3d58d10aafd9ac9355fdd16151607e37d65/Doc/tools/extensions/pyspecific.py#L679

I would not be averse to adding `gh-issue` as an alias for `gh`.
