### ISSUE TITLE
Additional repositories section mentions that cherry_picker is in core-workflow

### ISSUE THREAD

**Issue by lysnikolaou** [python/devguide#1093]
**Describe the bug**
The Additional Repositories section on the "Following Python’s Development" page mentions that `cherry_picker` is in the core-workflow repo, which is no longer true, since it's been moved to its own repository.

**Expected behavior**
Mention that `blurb` is on `core-workflow` and probably add links to the other repositories with tools around core-workflow.

**Screenshots**
![Screenshot 2023-05-05 at 12 38 24](https://user-images.githubusercontent.com/20306270/236436767-d31cb6fe-3075-4fad-8b0d-291c02b28380.png)

**Comment by 0x00zer0day** [comment]
Hello @lysnikolaou, I am new to the open source community and am interested in solving this issue. I understand that the "cherry_picker" needs to be removed from this section. What do you suggest I replace "cherry_picker" with?

**Comment by hugovk** [comment]
Done in https://github.com/python/devguide/pull/1094.
