### ISSUE TITLE
Clarify step 4 in pull request template

### ISSUE THREAD

**Issue by willingc** [python/devguide#110]
In both the devguide and CPython repos, the PR template (see [example](https://github.com/python/devguide/pull/106#issuecomment-279165704)) lists the steps for a new contributor to sign the CLA, add their GitHub username to bpo, and check if the bpo account shows the CLA as signed.

Adding a small visual to "Step 4: Adding GitHub user name to bpo account" would probably save maintainers from reminding people to add their GitHub user name. A small graphic similar to this would help:

<img width="347" alt="bpo_gh" src="https://cloud.githubusercontent.com/assets/2680980/22867185/d3aedcf8-f137-11e6-8469-d5f7861a1073.png">

**Comment by berkerpeksag** [comment]
Did we get any reports about this? I think the steps are quite easy to follow. The only vague part is

```rst
If you just signed the CLA, please wait at least **a day**  [...]
```

IMO https://github.com/python/the-knights-who-say-ni/pull/89 will make step 4 clearer.

**Comment by willingc** [comment]
@berkerpeksag Just a suggestion. I've seen a number of new contributors neglect adding their GitHub address to bpo, and then a maintainer has to remind. 

Looking at it from someone familiar with bpo, I agree that the text is clear. Yet, a new contributor will likely benefit from further guidance since they will likely not be familiar with bpo.

**Comment by brettcannon** [comment]
My only worry with adding an image is it will make an already large comment even larger and I would be worried about making it come off as intimidating (I tried to make it as friendly and self-explanatory as possible at the same time, hence its current length). I'm not opposed to providing a link to the image in the message, though.

**Comment by willingc** [comment]
@brettcannon Link to an image would be wonderful. :smile:

**Comment by brettcannon** [comment]
@willingc any ideas on where to host the image to provide the link? Or should we just link to https://cloud.githubusercontent.com/assets/2680980/22867185/d3aedcf8-f137-11e6-8469-d5f7861a1073.png ?

**Comment by willingc** [comment]
The PNG is pretty small. Perhaps create a static directory where the Pull Request template lives (knights who say ni repo?) and put it there. Though I suppose linking as you mention would be fine too.

**Comment by brettcannon** [comment]
Let's try using the link we already have. Did you want to make a PR for the bot, @willingc ?

**Comment by willingc** [comment]
Sure. I'll add it later this afternoon. Thanks @brettcannon.
