### ISSUE TITLE
Instructions for adding a new definition to the limited API don't work on platforms without `make`

### ISSUE THREAD

**Issue by AlexWaygood** [python/devguide#1102]
**Describe the bug**

In the devguide [here](https://devguide.python.org/developer-workflow/c-api/#adding-a-new-definition-to-the-limited-api), it states:

> Regenerate the autogenerated files using make regen-limited-abi. On platforms without make, run this command directly:
> 
> `./python ./Tools/scripts/stable_abi.py --generate-all ./Misc/stable_abi.toml`

I'm using a platform without `make`, so I went for the second option. Unfortunately, there's no such script! `Tools/scripts/stable_api.py` doesn't exist in the CPython repo currently. As such, the instructions didn't work.

**Expected behavior**

I expected the instructions to work

**Comment by encukou** [comment]
Ugh. Yes, looks like it was moved to `Tools/build/stable_abi.py` in https://github.com/python/cpython/pull/97963

There might be more:
```
$ git grep Tools/scripts
developer-workflow/c-api.rst:381:     ./python ./Tools/scripts/stable_abi.py --generate-all ./Misc/stable_abi.toml
developer-workflow/c-api.rst:388:    ./python ./Tools/scripts/stable_abi.py --all ./Misc/stable_abi.toml
internals/interpreter.rst:49:Some code objects are pre-loaded into the interpreter using ``Tools/scripts/deepfreeze.py``, which writes ``Python/deepfreeze/deepfreeze.c``.
testing/run-write-tests.rst:94:You can also execute the ``Tools/scripts/run_tests.py`` script as  found in a
```

**Comment by encukou** [comment]
False alarm: `internals/interpreter.rst` is 3.11-specific, and `Tools/scripts/run_tests.py` still exists.

https://github.com/python/devguide/pull/1103 should fix this.
