### ISSUE TITLE
https://docs.python.org/devguide/ is old

### ISSUE THREAD

**Issue by methane** [python/devguide#112]
https://docs.python.org/devguide/ still describe mercurial step.

Why there are two site to maintain?
Can't we use only http://cpython-devguide.readthedocs.io/ ?

**Comment by berkerpeksag** [comment]
I've purged Fastly cache. It should show up-to-date information now.

**Comment by methane** [comment]
close this for now.
But I don't understand why there should be two site yet...

**Comment by berkerpeksag** [comment]
I think the ultimate goal is to use RtD and redirect docs.p.o/devguide to RtD.
