### ISSUE TITLE
Document guidelines for when to use dynamically typed APIs

### ISSUE THREAD

**Issue by erlend-aasland** [python/devguide#1127]
We need to agree on guidelines for when to use and when to not use dynamically typed APIs.

See capi-workgroup/problems#31 (_The C API is weakly typed_)

In https://github.com/capi-workgroup/problems/issues/31#issuecomment-1602329178, @markshannon suggests:

```c
PyObject *obj, PyDictObject *dict;
PyObject_GetItem(obj);   // 👍 
PyDict_GetItem(dict);   // 👍 
PyObject_GetItem((PyObject *)dict); // Pointlessly inefficient
PyDict_GetItem((PyDictObject *)obj); // Unsafe
```

**Comment by vstinner** [comment]
I suppose that a guideline should be decided in https://github.com/capi-workgroup/problems/issues/31 first.

**Comment by erlend-aasland** [comment]
> I suppose that a guideline should be decided in [capi-workgroup/problems#31](https://github.com/capi-workgroup/problems/issues/31) first.

Definitely!
