### ISSUE TITLE
Add Documentation For Contributing To CPython Using Github Codespaces

### ISSUE THREAD

**Issue by marlenezw** [python/devguide#1138]
**Describe the enhancement or feature you'd like**
I'd like to add documentation to show how to use Codespaces for CPython using the [devcontainer](https://github.com/python/cpython/tree/main/.devcontainer) file recently added. There has been some discussion about this issue [here](https://discuss.python.org/t/add-support-for-devcontainers-to-facilitate-github-codespaces-usage/21330) and several people mentioned documentation would be helpful. 

**Describe alternatives you've considered**
I've considered adding a page that describes the steps needed to contribute to CPython using Codespaces. I think this should be added under the Getting Started section of the devguide. 

**Additional context**
More information about codespaces can be found [here](https://github.com/features/codespaces).

**Comment by willingc** [comment]
Closing since #1144 has landed. Thanks @marlenezw
