### ISSUE TITLE
FAQ page is still in docs.python.org/devguide

### ISSUE THREAD

**Issue by Mariatta** [python/devguide#114]
FAQ section was removed in GH-27
Recently docs.python.org/devguide has been updated to reflect the github branch.

Somehow this page is still alive 😅 
https://docs.python.org/devguide/faq.html

Any idea of what should be done? 

The FAQ is referenced in https://docs.python.org/3/faq/general.html and this issue is related to https://github.com/python/cpython/pull/8

**Comment by brettcannon** [comment]
Just delete it again. 😄

**Comment by ned-deily** [comment]
I believe the problem is that the docs build job doesn't remove deleted pages.  I'll ask infra to manually remove it and also the patch.html page.

**Comment by ned-deily** [comment]
OK, https://docs.python.org/devguide/faq.html and https://docs.python.org/devguide/patch.html are now gone; you might need to refresh your browser to get the 404.

It might make sense to turn this issue into a request to get the docsbuild script to remove deleted pages when updating the on-line html (if such an issue does not already exist; this isn't the first time something like this has happened).

**Comment by brettcannon** [comment]
python/core-workflow#4 is about moving the devguide to Read the Docs and then adding a subdomain on python.org for the devguide. That would alleviate the custom infrastructure dependency.

**Comment by ned-deily** [comment]
The problem with deleted pages isn't limited to the devguide.  It affects all docs builds.

**Comment by Mariatta** [comment]
Thanks @ned-deily 
I'm not familiar with docsbuild script. Do you mean that the issue is something to be reported to https://github.com/sphinx-doc/sphinx/ ? If so, I will file a bug there :)

btw I just checked https://docs.python.org/devguide/faq.html  and https://docs.python.org/devguide/patch.html both are still active. Could there be caching issue?

**Comment by zware** [comment]
@Mariatta See https://github.com/python/docsbuild-scripts for the script that triggers the builds of everything on docs.python.org.

**Comment by Mariatta** [comment]
Aha! Thanks @zware will check it out :)

**Comment by ned-deily** [comment]
Grrr! They were deleted yesterday but I think the files came back because they also need to be deleted from the docs build directory that probably just gets copied over to the directory from which they are served (I don't have read access to the build directory).  I've asked the admins to remove both sets.  Hopefully, that will make them permanently go away.

**Comment by ned-deily** [comment]
The two pages are now gone again, with luck they will stay that way this time.  Since you've opened the issue under docsbuild-scripts, I guess we can close this one?

**Comment by Mariatta** [comment]
Sounds good :)
