### ISSUE TITLE
Would you be willing to insert a line-break at the end of every sentence in the Development Guide for Python?

### ISSUE THREAD

**Issue by Samuel-Muldoon** [python/devguide#1152]
**Inserting a Line-Break `\r\n` at the End of Every Sentence**

I find that documentation is easier to read if there is a line-break at the end of each and every complete sentence. 

![BEFORE_AND_AFTER_PICTURES_DEMONSTRATING_SUGGESTED_CHANGE](https://github.com/python/devguide/assets/56810295/e6065a70-8ad5-4207-acd5-b28b40a7ed0d)

Would you be willing to help ensure that each and every English sentence ends in a line-break?

**Comment by zware** [comment]
Can you provide any examples of this style elsewhere on the internet or in print?  I personally find the "after" example significantly *harder* to read; the extra vertical space implies that the three sentences are unrelated, when they're really just a single paragraph.

In the absence of significant evidence showing widespread benefits to this change, I'm afraid the answer is sorry, but no.
