### ISSUE TITLE
Update internals section of devguide

### ISSUE THREAD

**Issue by markshannon** [python/devguide#1159]
# Documentation

The internals section of the devguide https://devguide.python.org/internals/ could do with updating.

The [compiler page](https://devguide.python.org/internals/compiler/) could do with updating. Particularly the "Introducing New Bytecode" doesn't belong here, and the "Known Compiler-related Experiments" should just be deleted.

The internals also needs links to the up to date docs in https://github.com/python/cpython/tree/main/Objects

**Comment by Lincoln-developer** [comment]
thanks , l appreciate.

**Comment by Lincoln-developer** [comment]
@markshannon and @zware , well I am actually looking at the html code for the compiler page, like the way the issue states; 'Introducing New Bytecode' and 'Know Compiler Related Environments' don't belong in the compiler page and should just be deleted, so a bit to be more clear, should I just deleted the headers for the two wordings only or the whole sections for both.

**Comment by Lincoln-developer** [comment]
And if deleted, are they supposed to be somewhere else, if yes where could that be ?
