### ISSUE TITLE
Require to backport all documentation and tests changes to stable Python branches

### ISSUE THREAD

**Issue by vstinner** [python/devguide#1168]
All documentation and tests changes done in the Python main branch should be backported to stable branches (currently 3.11 and 3.12). It should be documented in the devguide.

Context: https://github.com/python/cpython/issues/108303#issuecomment-1729024106

**Comment by hugovk** [comment]
This should probably go in https://devguide.python.org/developer-workflow/development-cycle/

(https://devguide.python.org/getting-started/git-boot-camp/#backporting-merged-changes says how to backport, not why/when.)

**Comment by JacobCoffee** [comment]
Hi, I'd like to grab this if its untaken

**Comment by AA-Turner** [comment]
Go ahead, feel free to ping in the PR for feedback.

A

**Comment by JacobCoffee** [comment]
Also does this go along with #1069?

**Comment by AA-Turner** [comment]
I'd probably add a note below that list saying that documentation and tests may be backported to any bugfix branch. See also [Jelle's notes](https://jellezijlstra.github.io/cpython#backporting).

A

**Comment by JacobCoffee** [comment]
Hi @AA-Turner please see my changes - are they to little or just bad in general? 😅

**Comment by hugovk** [comment]
Fixed in https://github.com/python/devguide/pull/1169, thanks @JacobCoffee!

**Comment by vstinner** [comment]
Thanks.
