### ISSUE TITLE
Devguide §6.3 says Devguide issues are tracked on b.p.o.

### ISSUE THREAD

**Issue by JDLH** [python/devguide#117]
The Devguide, section [_6.3. Helping with the Developer’s Guide_](https://cpython-devguide.readthedocs.io/docquality.html#helping-with-the-developer-s-guide), says, "The Developer’s Guide uses the same process as the main Python documentation…. Bug reports and patches should be submitted to the [Python bug tracker](http://bugs.python.org/) using the `devguide` component." Note the link to bugs.python.org .

If the intention is to track Devguide issues at https://github.com/python/devguide/issues/, this should  get corrected. 

Also, the preceding parts of section 6 talk about using b.p.o as the issue tracker for "documentation". It would be good to make those parts clearer that they refer only to documentation which is not the Devguide.

**Comment by brettcannon** [comment]
You're right, the link is wrong and issues are tracking here on GitHub.

**Comment by ezio-melotti** [comment]
This has been fixed now, thanks for the report!
