### ISSUE TITLE
devguide should mention rules about "paragraph reflow" in the documentation

### ISSUE THREAD

**Issue by brettcannon** [python/devguide#12]
Originally from http://bugs.python.org/issue23320

**Comment by willingc** [comment]
Next action: add a brief section in `docquality.rst` perhaps under the section "Helping with Documentation issues"

- small documentation changes for content is preferred
- reflowing text is discouraged as it makes review more difficult (a core dev will reflow text if needed or ask you to reflow in a follow up PR)

**Comment by willingc** [comment]
Closing as #1018 will cover this issue.
