### ISSUE TITLE
Github organization link is secret and not accessible from core-dev guide

### ISSUE THREAD

**Issue by CuriousLearner** [python/devguide#124]
On visiting link: https://docs.python.org/devguide/coredev.html#github

The first sentence is "You will be added to the Python core team on GitHub."

The ``Python core team`` refers to a link to Github which is not accessible to anyone except for those who are part of the organization.

I'd like to suggest to either remove the link from the documentation or make the team visible to public.

This was initially reported at python bug tracker: http://bugs.python.org/issue29599

**Comment by CuriousLearner** [comment]
If this requires change like removing the link form the devguide, I'd be more than happy to pick this up!

**Comment by willingc** [comment]
Hi @CuriousLearner,

I agree that it would be helpful to have an indication that only core devs are able to access the link, make the link direct to a public team, or remove the link but not the text.

@mariatta Thoughts?

**Comment by Mariatta** [comment]
Thanks @CuriousLearner and @willingc :)
I vote for removing the link and keeping the text.

So, the change is to be made in coredev.rst:
```
You will be added to the `Python core` team on GitHub.
```

**Comment by CuriousLearner** [comment]
@Mariatta @willingc I've added a PR for the same.

**Comment by orsenthil** [comment]
Thank you! Merged: https://github.com/python/devguide/pull/127

**Comment by CuriousLearner** [comment]
Thanks @orsenthil !
