### ISSUE TITLE
Quantum Deep Learning

### ISSUE THREAD

**Issue by davidmerwin** [python/devguide#1252]
> Note: This repo is for the Python devguide. If you are requesting an
enhancement for the Python language or CPython interpreter,
then the CPython issue tracker is better
suited for this report: https://github.com/python/cpython/issues

**Describe the enhancement or feature you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by davidmerwin** [comment]
> > Note: This repo is for the Python devguide. If you are requesting an
> enhancement for the Python language or CPython interpreter,
> then the CPython issue tracker is better
> suited for this report: https://github.com/python/cpython/issues
> 
> **Describe the enhancement or feature you'd like**
> A clear and concise description of what you want to happen.
> 
> **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context**
> Add any other context or screenshots about the feature request here.

@kubeinit-bot

**Comment by davidmerwin** [comment]
> > Note: This repo is for the Python devguide. If you are requesting an
> enhancement for the Python language or CPython interpreter,
> then the CPython issue tracker is better
> suited for this report: https://github.com/python/cpython/issues
> 
> **Describe the enhancement or feature you'd like**
> A clear and concise description of what you want to happen.
> 
> **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context**
> Add any other context or screenshots about the feature request here.

@davidmerwin

**Comment by Mariatta** [comment]
Please don't spam here.
