### ISSUE TITLE
Document backport and cherry-pick labels

### ISSUE THREAD

**Issue by Mariatta** [python/devguide#126]
There should be a documentation explaining what to do with the labels `needs backport to X.Y` and `cherry-pick for X.Y`. Perhaps as a new section in committing.rst? 

I think this is the current workflow: (as discussed in https://github.com/python/core-workflow/issues/23)

- Apply `needs backport to X.Y` label to the PR against `master`.
- Once `master` PR is approved and merged, create the cherry-pick PR. 
- Remove `needs backport to X.Y` label from `master` PR
- Apply the `cherry-pick for X.Y` to the cherry-pick PR.
- Prefix the cherry-pick pr description with `[X.Y]`
- Issue can be closed once all cherry-pick PRs have been merged.

Where `X.Y` is one of the maintenance branches, e.g. `2.7`, `3.5`, `3.6`

Related question: Can I assume that the core developer who merged the `master` PR will do the backport?

Thanks :)

**Comment by berkerpeksag** [comment]
+1 from me. We probably need to wait for a bit to settle on the exact workflow before starting to document it.

We could probably cover the GitHub part in http://cpython-devguide.readthedocs.io/committing.html#backporting-changes-to-python-3-6-or-older-version (or split it to two separate subsections?)

> Related question: Can I assume that the core developer who merged the master PR will do the backport?

+1. This is also my assumption.
