### ISSUE TITLE
Document env var style

### ISSUE THREAD

**Issue by hugovk** [python/devguide#1285]
In https://discuss.python.org/t/change-environment-variable-style/35180 we decided to use underscores in new environment variable names introduced in Python 3.13+.

For example, `PYTHON_CPU_COUNT` instead of `PYTHONCPUCOUNT`.

Let's document it somewhere in the devguide.

**Comment by hugovk** [comment]
Please see PR https://github.com/python/devguide/pull/1300.

**Comment by ezio-melotti** [comment]
Are there any mechanisms in place to e.g. ignore the `_`s so that both `PYTHON_CPU_COUNT` and `PYTHONCPUCOUNT` work?

**Comment by hugovk** [comment]
Inside Python? Maybe, but we'd need to decide what to do when both exist, with different values, which could be set by different groups. Who wins? See https://discuss.python.org/t/change-environment-variable-style/35180/7, and the Discourse thread is the place to discuss this :)
