### ISSUE TITLE
Mention grouping sphinx object definitions

### ISSUE THREAD

**Issue by nineteendo** [python/devguide#1321]
### Describe the enhancement or feature you'd like

Could we mention how to group sphinx object definitions?

```rst
.. data:: ParamSpecArgs
          ParamSpecKwargs
```

### Additional context

- https://github.com/python/cpython/issues/118030
- https://discuss.python.org/t/grouping-sphinx-object-definition-directives/52745

**Comment by hugovk** [comment]
For reference, PR: https://github.com/python/devguide/pull/1322

Let's close this issue, we already have a CPython issue and discuss thread, and now PR.
