### ISSUE TITLE
Please invite me to this organization (hi-tech-AI)

### ISSUE THREAD

**Issue by hi-tech-AI** [python/devguide#1323]
Hello, I hope everything is doing well.
I want to join this organization because I'm very fascinated to Python Development.
I want to be a member of this organization.
My GitHub username is hi-tech-AI.
Please let me invite to this organization.
Thank you so much.

**Comment by hugovk** [comment]
Welcome! You don't need to join the org to contribute, see https://devguide.python.org for more info and ask questions at https://discuss.python.org/c/users/7
