### ISSUE TITLE
Update Devguide about pull request commit documentation.

### ISSUE THREAD

**Issue by lulouie** [python/devguide#133]
I think the documentation of pull request commit should be improved, the current version with `3. Subitting` isn't that clear for people who were new to GitHub or Python CPython development process.

**Comment by ezio-melotti** [comment]
This is a duplicate of #103, but since you have a PR I'll leave it open.

The PR looks good -- I'm going to review it in detail and merge it tomorrow.

**Comment by lulouie** [comment]
#140 Close this.
