### ISSUE TITLE
Page about test coverage contains a broken link to `lcov`

### ISSUE THREAD

**Issue by tomasr8** [python/devguide#1355]
The link to `lcov` results in a 404:

https://github.com/python/devguide/blob/47e18d944abbb14a8205acd90fb68faf6a99a6fb/testing/coverage.rst?plain=1#L309

Should we perhaps link to the project's GitHub page?

**Comment by zware** [comment]
Looks like it; do you want to submit a PR?

**Comment by tomasr8** [comment]
> do you want to submit a PR?

Sure :) Coming in a bit
