### ISSUE TITLE
"Reporting an issue" section is out of sync with actual github options

### ISSUE THREAD

**Issue by skirpichev** [python/devguide#1403]
Current text:
https://github.com/python/devguide/blob/8fcb7a5ccc96751299cb2e8bf5c8ad4fa8eaeb59/triage/issue-tracker.rst?plain=1#L57-L69

Instead we have available:
* Bug report
* Crash report
* Documentation
* Feature or enhancement
* Report a security vulnerability
* Getting help
* Proposing new features

Last two point to d.p.o.

I'm not sure if devguide should list all available options, rather ones that always be present and/or relevant for following text.  Say:
```
 First you need to select what kind of problem you want to report. The 
 available choices include, for example: 
  
 * **Bug report**: an existing feature isn't working as expected; 
 * **Documentation**: there is missing, invalid, or misleading documentation; 
 * **Feature or enhancement**: suggest a new feature for Python; 
```

**Comment by AA-Turner** [comment]
> rather ones that always be present and/or relevant for following text

Your suggested text looks good as a starter for ten.

A
