### ISSUE TITLE
There is a TODO in the "fixing-issues.rst" file

### ISSUE THREAD

**Issue by Mariatta** [python/devguide#1409]
I noticed a TODO item in the fixing-issues.rst

```
.. TODO: add something about no active core developer for the area?
```

Are we still planning to do this? Or should we remove it?

Action items:
- Either complete the TODO (create PR for it)
- Or remove the TODO

**Comment by hugovk** [comment]
Added by @ned-deily 14 years ago in https://github.com/python/devguide/commit/ce2fc9ecbc9f866c1bfba52ebef08bb0e8ba7445.

**Comment by ned-deily** [comment]
> Added by @ned-deily 14 years ago in [ce2fc9e](https://github.com/python/devguide/commit/ce2fc9ecbc9f866c1bfba52ebef08bb0e8ba7445).

If you are looking for insight from me on that comment, I have none to give, sorry!

**Comment by hugovk** [comment]
No problem :) Let's remove it.
