### ISSUE TITLE
Incluye el vínculo 

### ISSUE THREAD

**Issue by Malandro9493** [python/devguide#1477]
"https://example.com/	" https"	" example.com"	nulo	« la cadena vacía »	nulo	nulo
https://localhost:8000/search?q=text#hello	" https"	" localhost"	8000	« " search" »	" q=text"	" hello"
urn:isbn:9780307476463	" urn"	nulo	nulo	" isbn:9780307476463"	nulo	nulo
file:///ada/Analytical%20Engine/README.md	" file"	nulo	nulo	« " ada", " Analytical%20Engine", " README.md" »	nulo	nulo"

**Comment by hugovk** [comment]
@Malandro9493 Please stop spamming, this is your second one after https://github.com/python/devguide/issues/1476.
