### ISSUE TITLE
CPython contribution docs reference missing /issuetracker page

### ISSUE THREAD

**Issue by strugee** [python/devguide#156]
https://cpython-devguide.readthedocs.io/pullrequest.html#licensing (and presumably other pages in this project) references https://cpython-devguide.readthedocs.io/issuetracker, but this page returns 404 Not Found.

(Moved from https://bugs.python.org/issue30001)

**Comment by Mariatta** [comment]
Thanks for the report @strugee 
A new contributor is currently working on this issue, so I'm assigning this to myself to not duplicate anyone's effort.

**Comment by strugee** [comment]
@Mariatta that's phenomenal! Yay for more contributors :tada:
