### ISSUE TITLE
Document when it's okay to dismiss another core dev's review

### ISSUE THREAD

**Issue by brettcannon** [python/devguide#161]
If a core dev requests changes, when it is okay to dismiss that request? Discussion in python/core-workflow#36 and the reached conclusion that we should probably document.

**Comment by Thtboi420** [comment]
Sent using Zoho Mail


---- On Mon, 10 Apr 2017 16:36:01 -0700 notifications@github.com wrote ----

If a core dev requests changes, when it is okay to dismiss that request? Discussion in python/core-workflow#36 and the reached conclusion that we should probably document.
