### ISSUE TITLE
Add how to pull (checkout) a PR locally at "3.4.1. How to Review a Pull Request"

### ISSUE THREAD

**Issue by lulouie** [python/devguide#168]
After reading this chapter, I think it should adding instruction how to checkout PR locally.

The GitHub instruction is here: [Checking out pull requests locally](https://help.github.com/articles/checking-out-pull-requests-locally/)

**Comment by Mariatta** [comment]
Thanks :) We have it written here.
https://docs.python.org/devguide/gitbootcamp.html#downloading-other-s-patches

**Comment by lulouie** [comment]
@Mariatta Thanks for the note, I made another PR for adding reference to this at `pullrequest.rst`
