### ISSUE TITLE
Add PDF build

### ISSUE THREAD

**Issue by willingc** [python/devguide#172]
We currently have an HTML zip that is downloadable from ReadTheDocs. It would be helpful to also build and offer a PDF for download. Possibly epub too.

**Comment by lulouie** [comment]
For epub, it can generate by `make epub`; for pdf, there is a `rst2pdf` package can use.

On ReadTheDocs, `advance` setting can both enable pdf and epub to build and download.

**Comment by berkerpeksag** [comment]
What's the use case? Most of the devguide requires a computer and a python/cpython checkout to follow its content. I don't think it's suitable for a morning read on an ebook reader :) I'd prefer avoid using more RtD resources.

**Comment by willingc** [comment]
Some of us periodically download PDF and ebooks to use as a reference, especially when off-line or in areas with poor internet access. It's a simple addition that requires very little effort or resource. @berkerpeksag It could also help those with insomnia ;-)

**Comment by brettcannon** [comment]
I initially turned it off as I wasn't sure if anyone was going to want them, but now that we have a request I have ticked the boxes for PDF and epub.

**Comment by willingc** [comment]
Thanks @brettcannon 👍
