### ISSUE TITLE
Update the section about backporting changes

### ISSUE THREAD

**Issue by Mariatta** [python/devguide#173]
The section: 
http://cpython-devguide.readthedocs.io/committing.html?highlight=backport#backporting-changes-to-python-3-6-or-older-version
has instructions on how to apply a patch to master, which is not desirable in the current workflow. We should be working on branches other than master.

I think this should be updated somehow. Maybe also consider merging it with the next section http://cpython-devguide.readthedocs.io/committing.html?highlight=backport#backport-and-cherry-pick-labels

**Comment by ncoghlan** [comment]
I'd suggest updating it to show using `git log -10 --oneline` to get a list of the recent commit hashes and the first line of their commit messages.
