### ISSUE TITLE
Clarify position on spaces after sentence ending period

### ISSUE THREAD

**Issue by DimitrisJim** [python/devguide#174]
I've seen this a couple of times when a review for doc changes is done: a user forgets to add two spaces after a period and a comment urging him to do so is made. Problem is, the section on writing docs doesn't really state a preference for this in any way:

>  A sentence-ending period may be followed by one or two spaces; while reST ignores the second space, it is customarily put in by some users, for example to aid Emacs’ auto-fill mode.

Since, it seems to me, the double space after the period is strongly preferred, should the text above be changed to state this preference or, instead of simply stating a preference, make it clear that only two spaces are to be used?

>  A sentence-ending period should be followed by two spaces; while reST ignores the second space, using it aids external tools used for writing documentation, for example, aiding Emacs’ auto-fill mode.

**Comment by willingc** [comment]
Hmm... Current documentation best practices typically recommend one space after a period. As for CPython style, I would hope that we are flexible on one or two spaces for reST.

**Comment by brettcannon** [comment]
I personally prefer one space, but I don't think we have ever really enforced that (I honestly had never seen a comment about it until our move to GitHub; maybe GitHub just makes it more obvious in their UI compared to Rietveld?). I'm afraid this is  going to require more of a python-dev discussion to decide if we actually care to enforce anything or just let people do what they want.

**Comment by terryjreedy** [comment]
I am old enough to have been taught 2 spaces after sentence ending . when typing.  It is an old habit, and I probably prefer the look of 2 in raw source like this.  But I can deal with either. StackOverflow is forgiving and displays the same space in formatted text with either 1 or 2 spaces.  I think we should be too.  If there is a real concern, someone should write a commit hook that will standardize the spacing.

**Comment by pfmoore** [comment]
I was taught 2 spaces *for text that was to be displayed monospaced, e.g., on a typewriter*. For formatted text, I believe that TeX might have handled two spaces in input differently from 1 space, but that's the only case I'm even remotely aware of. And I think Emacs (and maybe Vim) react differently to double spaces. But that's a matter for how users configure their tools. Formatted versions of the docs should look the same regardless, so I don't think it should matter in practice.

+1 from me on allowing either convention for input.

**Comment by DimitrisJim** [comment]
It seems there's no one advocating strict usage of two spaces so I guess the python-dev discussion might not be needed :-). I think it's a good idea to leave this issue open for a bit longer and then close it if no other opinions surface.

**Comment by bitdancer** [comment]
restructured text is designed to be displayed monospaced when viewed as text (as opposed to when reformatted by some ReST consuming tool), which is why I believe the two space rule applies.  I don't care about it being made a requirement, as long as I can use two spaces in all the docs I edit.  But I do strongly prefer it.

**Comment by ezio-melotti** [comment]
+1 to what @bitdancer said.  I always use two.

**Comment by willingc** [comment]
Closing this issue as the [devguide](https://devguide.python.org/documenting/?highlight=spaces#use-of-whitespace) mentions either one or two spaces after a sentence is acceptable.
