### ISSUE TITLE
A couple of issues with compiler.rst

### ISSUE THREAD

**Issue by DimitrisJim** [python/devguide#181]
There's a couple of issues I've found, I'm creating this issue to see if some of them were intentional.

I'm not sure if the following were intentional or not:

 - Many of the functions and filenames aren't highlighted in any way. This fact leads to, at least in my opinion, harder to read sentences. Backticks and `:file:` directives could be used. 
 - The `C` snippet isn't highlighted with a `code-block` directive. 
 - A couple of macros contain the type for the arguments they receive, others don't. 

Some changes that need to be made: 

 - `NEW_BLOCK` was removed in `3.6`, if I'm not mistaken. 
 - `PyEval_EvalFrameEx` was changed with PEP 523, `PyEval_EvalFrameDefault` contains the big switch as mentioned.

I've probably missed some other functions that were renamed/tweaked, I'll keep checking to see if anything else is needed. 

---

All in all, this file is a really useful resource for anyone interested in the CPython compiler; it should be polished up and, if possible, linked in `exploring.rst` in some way.

**Comment by brettcannon** [comment]
All of the formatting issues are because I originally wrote that doc as an informational PEP before I wrote the original version of the devguide (which makes me realize how much I write 😅 ). So fixing the formatting of the page to utilize reST better is totally fine.
