### ISSUE TITLE
Mention the "Green Tree Snakes" AST guide

### ISSUE THREAD

**Issue by ncoghlan** [python/devguide#184]
Via a link in the standard library's AST module docs, I just learned of https://greentreesnakes.readthedocs.io/en/latest/index.html

I think this would make an excellent addition to https://docs.python.org/devguide/exploring.html, and would probably be worth referencing from https://docs.python.org/devguide/compiler.html as well.

**Comment by willingc** [comment]
I agree. @takluyver has developed quite a lot of cool Python things. This guide is a helpful one.

**Comment by takluyver** [comment]
:smiley: thanks!

**Comment by DimitrisJim** [comment]
I think it would make a nice addition too. Though, since I can't see in which table of `exploring.rst` it could be added, I think some restructuring of the tables might be needed first.
