### ISSUE TITLE
Promote helping with reviews more

### ISSUE THREAD

**Issue by brettcannon** [python/devguide#194]
This might fall out as part of #189 , but as of right now all of the highly promoted activities for people to contribute by are (in order of the index):

1. Docs
2. Test coverage
3. Silence warnings
4. Fixing issues from buildbots
5. Fixing "easy" issues
6. Triaging issues

There is no mention of helping to review PRs. And idea 6 for helping triage issues is at the end. Unfortunately triaging issues and helping to review PRs can be the most helpful as they help *reduce* the workload for core devs versus ideas 1 - 5 which *make* work for core devs.

Now it might not entirely make sense to have people start with triage and code review, but the point should be made somehow that activities that reduce workload is **really** important.

**Comment by terryjreedy** [comment]
One cannot edit headers right away, but one can evaluate issues and leave comments right away.  1. Is issue bug or enhancement? 2. If bug, present on current release or different OS or system?* 3. If enhancement, is it useful?  Is function already present?  That is how I started and would advise others to start.

* Some issues really need testing on multiple systems, and this is something most people cannot do alone.

**Comment by brettcannon** [comment]
@terryjreedy hopefully that's covered by https://cpython-devguide.readthedocs.io/tracker.html#helptriage (which should probably be merged with https://cpython-devguide.readthedocs.io/triaging.html with a clear separation of what anyone can do and what people with Contirbutor privileges can do).

**Comment by Mariatta** [comment]
Maybe include the following shortcuts:

Open PRs awaiting reviews: is:pr is:open label:"awaiting review" 
https://github.com/python/cpython/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Aopen%20label%3A%22awaiting%20review%22

Open PRs awaiting core reviews:
https://github.com/python/cpython/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Aopen%20label%3A%22awaiting%20core%20review%22%20
