### ISSUE TITLE
Improve "Commit Messages" section in committing.rst

### ISSUE THREAD

**Issue by berkerpeksag** [python/devguide#199]
It would be great if we could tweak the section at http://cpython-devguide.readthedocs.io/committing.html#commit-messages a bit. For example,

1. It doesn't include `(GH-NNNN)` suffix in the first line:
    ```
    bpo-42: the spam module is now more spammy. (GH-1234)
    ```
2. It doesn't mention about stripping unnecessary parts when doing the merge (see https://github.com/python/cpython/commit/6924ed55c9807d69757e03bbe1caeec1104efacb for example)
3. It doesn't talk about what to do with backport PRs (e.g. should we drop the backport PR number from the title?)
    Currently, we do have:

    ```
    bpo-42: the spam module is now more spammy. (GH-1234) (#4242)
    ```

    #4242 is the backport PR here, but it's rarely useful and it can be seen by using the GitHub UI.

    I suggest stripping it and only keep the original PR number:

    ```
    bpo-42: the spam module is now more spammy. (GH-1234)
    ```

    Another question is that should we add `[X.Y]` to commit messages too or should we only add it to the PR title?
4. It doesn't talk about what to do with `GH-NNNN` annotations when the first line of the commit message is too long. See https://github.com/python/cpython/commit/edef358ed6d05f927bf1636cc5a920a9d868b131 for example. Should we move the annotation to the end of the commit message in this case? For example:

    ```
    bpo-29196: Removed old-deprecated classes Plist, Dict and _InternalDict
    in the plistlib module.

    Dict values in the result of functions readPlist() and readPlistFromBytes()
    are now exact dicts.

    Pull request: GH-488
    ```

**Comment by Mariatta** [comment]
Sounds good.

Some comments:

> It doesn't mention about stripping unnecessary parts when doing the merge (see python/cpython@6924ed5 for example)

It's briefly mentioned in [here](http://cpython-devguide.readthedocs.io/gitbootcamp.html#accepting-and-merging-a-pull-request), but I think makes more sense now to move this into **Committing** section.

> should we add [X.Y] to commit messages too or should we only add it to the PR title?

I'm inclined to keep the [X.Y] in the commit message, only because cherry_picker.py is doing this by default. I also understand that not everyone uses it, and also cherry_picker.py is supposed to be temporary until a bot is in place. So I won't oppose omitting it from the commit message.

**Comment by brettcannon** [comment]
I took a small poll here at the PyCon US sprints and basically everyone uniformly said "keep the branch label" and "don't care about the listed PRs", so basically just keep the title intact compared to what we have people specify for PRs currently.

**Comment by Mariatta** [comment]
@berkerpeksag I think everything has been addressed, so I'm closing this. Please reopen if it turns out that I miss something. Thanks.

**Comment by berkerpeksag** [comment]
@Mariatta thank you, it looks pretty good to me. I missed PR #275. I've just opened #288 for my tweaks.
