### ISSUE TITLE
Mention core-workflow mailing list / repo

### ISSUE THREAD

**Issue by Mariatta** [python/devguide#202]
It should worth mentioning in the devguide somewhere that there's core-workflow mailing list and core-workflow repo.

**Comment by ncoghlan** [comment]
New entries in https://docs.python.org/devguide/communication.html would probably make sense for that. That page is also likely a reasonable place to list "Additional Repositories" (for core-workflow, the benchmark suite, and probably the issue tracker).

**Comment by matrixise** [comment]
@ncoghlan issue tracker ? b.p.o or the issue tracker of the infra ?

**Comment by matrixise** [comment]
Hi @ncoghlan and @Mariatta 

I just created the PR for this issue, need your reviews.

Thank you

**Comment by matrixise** [comment]
please @ncoghlan and @Mariatta, could you review this PR ?

Thank you

**Comment by Mariatta** [comment]
Closed in #220

**Comment by Mariatta** [comment]
Thanks for the PR @matrixise 🌮
