### ISSUE TITLE
Quoting for config alias.pr

### ISSUE THREAD

**Issue by terryjreedy** [python/devguide#217]
The following in Bootcamp does not work on windows because the quoting is wrong for Windows:
git config --global alias.pr '!sh -c "git fetch upstream pull/${1}/head:pr_${1} && git checkout pr_${1}" -'
git responds with a usage message.

Windows only recognizes "..." quotes on a command line.  Reversing the quotes creates the alias.
git config --global alias.pr "!sh -c 'git fetch upstream pull/${1}/head:pr_${1} && git checkout pr_${1}' -"
Subsequently, "git pr ####" works because git finds the 'sh' included with Git for Windows.

If the reversed form works on *nix, the current line can just be edited.  If not, then the new line should be added with a 'for Windows' note.

**Comment by Mariatta** [comment]
hmm I tried reversing the quotes on my machine (MacOS) and it doesn't work

```
$ git config --global alias.pr "!sh -c 'git fetch upstream pull/${1}/head:pr_${1} && git checkout pr_${1}' -"
-bash: !sh: event not found
```

So we need to add a note that says "on windows, reverse the quotes" something like that?

**Comment by terryjreedy** [comment]
"On Windows, reverse the single (') and double (") quotes." should do it.
