### ISSUE TITLE
Add link to documentation in the GitHub repo description

### ISSUE THREAD

**Issue by willingc** [python/devguide#22]
It's helpful for users to have a link to the documentation in the GitHub repo's description. Add http://cpython-devguide.readthedocs.io/en/latest/ 

Change must be made by a developer with privileges on the repo.

<img width="716" alt="screen shot 2016-07-23 at 9 48 55 am" src="https://cloud.githubusercontent.com/assets/2680980/17079087/b94e0fa0-50ba-11e6-9260-3935df25b6d7.png">

**Comment by brettcannon** [comment]
Done!
