### ISSUE TITLE
broken links and 404

### ISSUE THREAD

**Issue by matrixise** [python/devguide#221]
I have executed `make linkcheck` and I have some broken links.
```
http://docs.buildbot.net/current/manual/cfg-buildslaves.html#latent-buildslaves - Anchor 'latent-buildslaves' not found
http://news.gmane.org/ - 404 Client Error: Not Found for url: http://news.gmane.org/
http://scan5.coverity.com:8080/ - 503 Server Error: Service Unavailable for url: http://scan5.coverity.com:8080/
https://www.python.org/download/releases/3.4.4/ - 404 Client Error: OK for url: https://www.python.org/download/releases/3.4.4/
```

for news.gmane.org I think the project is dead but there is a new maintainer and the current url `news.gmane.org` does not work but there is a replacement: http://home.gmane.org/

for the release 3.4.4, I have this link: https://www.python.org/downloads/release/python-346/

for buildbot, we could remove the anchor

and scan5.coverity.com, do we continue to use it ?

thank you

**Comment by zware** [comment]
For the buildbot link, just do `s/current/0.8.14/` since that's the version we're running.  Alternately, `s/buildslaves/workers/g`.

**Comment by terryjreedy** [comment]
news.gmane.org still works for nntp, but apparently not for http(s).

**Comment by willingc** [comment]
PR #223 is open and needs a rebase.
