### ISSUE TITLE
Add a reference link to the "Python Extension Patterns" guide?

### ISSUE THREAD

**Issue by ncoghlan** [python/devguide#230]
I recently stumbled across https://pythonextensionpatterns.readthedocs.io, and I think it's an excellent introduction to the idioms of the Python C API for folks that already know C, but aren't yet familiar with the Python C API specifically.

I figure that kind of guide may also be useful to folks taking their first steps into CPython's C code.

**Comment by mlouielu** [comment]
+1 for this in the devguide, and I think the greensnake (ast guide) should put into it.

**Comment by matrixise** [comment]
Hi @ncoghlan 
It's just a small section but at least, there are a link to the official documentation and to the introduction

See this PR: https://github.com/python/devguide/pull/246

**Comment by Mariatta** [comment]
Closed in https://github.com/python/devguide/pull/279
