### ISSUE TITLE
Update links to point to https://devguide.python.org/

### ISSUE THREAD

**Issue by brettcannon** [python/devguide#231]
Yes, the subdomain now works. 😄

**Comment by Mariatta** [comment]
Yay! 🎉 
Can you change the link on GitHub? 😀 

<img width="593" alt="screen shot 2017-06-21 at 6 41 20 pm" src="https://user-images.githubusercontent.com/5844587/27413632-6a00f7de-56b1-11e7-9399-1e69d6a1ee2e.png">

**Comment by Mariatta** [comment]
So, replace these links:
- https://docs.python.org/devguide
- http://cpython-devguide.readthedocs.io

with

- https://devguide.python.org

Right? Thanks.

I think this will be a good task for a first timer :)

**Comment by Mariatta** [comment]
Let's hold this off until #232 is resolved :)

**Comment by brettcannon** [comment]
I also don't expect many mentions of the link since reST makes it so we can use relative links that are auto-generated, but I figured it wouldn't hurt to do a quick grep for the old domains.

**Comment by Mariatta** [comment]
Cool, thanks for the clarification.
I think there are a few hardcoded links from CPython docs, and also in the message by the-knights-who-say-ni.
I've recruited a first-time contributor, and they're interested to work on this. Stay tuned.

**Comment by Mariatta** [comment]
I created [bpo-30737](http://bugs.python.org/issue30737)
