### ISSUE TITLE
Links don't work in the new URL 

### ISSUE THREAD

**Issue by Mariatta** [python/devguide#232]
From https://devguide.python.org/

click on `set up` link or setup guide link which points to https://devguide.python.org/setup/#setup

It says "Sorry this page does not exist yet"

**Comment by brettcannon** [comment]
If you look from http://cpython-devguide.readthedocs.io you discover the URL should be http://cpython-devguide.readthedocs.io/setup.html#setup and that's actually what the page on devguide.python.org has. So my suspicion is theres a URL rewrite rule that was misconfigured. I've emailed Mark about this (on my phone so no @ completion to mention him on this issue).

**Comment by brettcannon** [comment]
Looks like if we can't get this easily fixed we can turn on Sphinx HTMLDir building on RTD: builders.html#sphinx.builders.html.DirectoryHTMLBuilder. We could then turn on redirects from HTML to HTMLDir: http://docs.readthedocs.io/en/latest/user-defined-redirects.html#sphinx-redirects (or vice-versa).

**Comment by brettcannon** [comment]
Actually not vice-versa because that leads to a redirect loop, so HTML -> HTMLDir is the only option (just need to check if anything breaks if the build type is changed).

**Comment by brettcannon** [comment]
OK, I went ahead and went with my quick fix to build the docs using the HTMLDir builder and then setting up a redirect from HTML -> HTMLDir and everything seems to work!

@MarkMangoba
