### ISSUE TITLE
Document how to add a new file or a new directory

### ISSUE THREAD

**Issue by vstinner** [python/devguide#241]
The issue title seems trivial, but in practice there are many traps. See for example: https://github.com/python/cpython/pull/2851/files Adding a new test directory requires to modify Makefile.pre.in and PCbuild/lib.pyproj.

**Comment by ncoghlan** [comment]
Adding new C files can also be trickier than it seems at first glance, as even though forgetting that will give you immediate build failures, you still need to know where to make the modifications for both autotools and MSVC in order to get pre-merge CI to pass.

**Comment by ncoghlan** [comment]
I'm not sure where you'd put this info in the current dev guide though - we don't really cover the build process right now beyond what's in https://devguide.python.org/setup/#compiling-for-debugging

It may make sense to expand https://devguide.python.org/setup/#troubleshooting-the-build into a new top level section on the build process, akin to the sections on changing the grammar or working on the compiler.

**Comment by ezio-melotti** [comment]
If I add a new file in a place that requires additional steps, do I get any error?
I think I would first try, then get an error, and then go look for a solution, so it makes sense to document this in the troubleshooting section.

**Comment by vstinner** [comment]
I lost track of this issue and apparently no one is available to work on it, so I prefer to close the issue.
