### ISSUE TITLE
Document working on other releases

### ISSUE THREAD

**Issue by csabella** [python/devguide#249]
Hi,

I couldn't figure out how to sync and work on a release other than master until I found this thread on core-mentorship.  If this isn't in the devguide already, would it be valuable to add?  I know you don't want to copy everything into the devguide, but this:

git checkout origin/2.7
git checkout -b 2.7

was not something I could come up with and I also couldn't find it by googling.

https://mail.python.org/mailman/private/core-mentorship/2017-June/004025.html

Thanks!

**Comment by Mariatta** [comment]
I think the two can be combined into
```
git checkout -b 2.7 origin/2.7 
```
which is similar to what's mentioned in https://devguide.python.org/gitbootcamp/#creating-and-switching-branches for branching off local `master`.
Perhaps in that section we can add this example for branching off `origin/<branch>` or `upstream/<branch>.

**Comment by csabella** [comment]
Thanks, Mariatta, that makes sense now - that the branch would be the release name.  I just couldn't figure out these things on my own:
1.  Naming a local branch `2.7` in order to sync it with my remote (`origin`).
2.  And, as you said, that you would use `origin/<branch>` or `upstream/<branch>` to create that new branch.

I don't remember creating `master` and all the working branches that I've created have been over the master, so I just didn't know how to reach the other releases.  Now that I've done it, I have a better understanding of branches and of releases.
