### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by ncoghlan** [python/devguide#252]
Should the developer guide have its own license file?

**Comment by Mariatta** [comment]
I think so 😄  
The same License in [core-workflow](https://github.com/python/core-workflow/blob/master/LICENSE)? or something else?

**Comment by brettcannon** [comment]
Whatever @VanL tells us the license should be. 😉 Not sure if it should be different for documentation.

**Comment by ncoghlan** [comment]
Yeah, this actually came up when I was picking the initial license for https://github.com/python/redistributor-guide/issues/1

While I picked the Apache Software License for now (since that's what core-workflow uses, and its one of the inbound licensing options when signing the PSF CLA), as a general principle, the OSI licenses aren't recommended for primarily documentation focused projects.

My personal choice would have been CC-BY, but GitHub doesn't appear to offer the Creative Commons licenses in its default license picker, and it's not clear to me whether or not CC-BY would interact properly with the PSF CLA (as that allows the PSF to relicense contributions under an *open source* license, which may not cover relicensing under an open documentation license).

Isn't copyright fun? :)

**Comment by brettcannon** [comment]
I've emailed @VanL to weigh in here on the preferred license for docs and for new code so we can document it in the devguide somewhere.

**Comment by brettcannon** [comment]
Heard back from @VanL and he said, "Prefer CC0. CC-BY is ok, as long as we also have a section in the docs that points to the commit log as the place where attribution is given."

**Comment by ncoghlan** [comment]
I'm fine with CC0 - these are needs-driven docs, so if folks want to borrow and repurpose them, we don't really mind either way whether they give attribution or not.
