### ISSUE TITLE
Delete the "Mercurial for git developers" page

### ISSUE THREAD

**Issue by ezio-melotti** [python/devguide#258]
[The mercurial for git developers page](https://github.com/python/devguide/blob/master/gitdevs.rst) page has been updated to include a note that says:

> While most of the work for Python is now done in Git, there are a couple ancillary repositories that still use Mercurial, and thus this document exists those who wish to help with those ancillary repositories.

AFAIK the only repos that still use Mercurial are the ones for bugs.python.org.  The structure of those repos is fairly simple and the activity is low, so most of the information included in that page is not relevant to them.

Can the page be removed?

**Comment by Mariatta** [comment]
+1 for removing :)

**Comment by ezio-melotti** [comment]
Merged, thanks for the review!
