### ISSUE TITLE
Cannot build devguide in virtual environment on Windows

### ISSUE THREAD

**Issue by jeff5** [python/devguide#267]
On Windows `make html` does nothing.

There are several problems here:
1. There's a use of `goto` inside parenthes. Yeah, it ought to work but [it doesn't reliably](https://ss64.com/nt/syntax-brackets.html). In fact, it stops the action dead.
2. A virtual environment is not set up for you as claimed in the guide.
3. The python command used is py -3 which ignored the active venv I created. (Not sure why, but it's not how the Unix Makefile works anyway.) 

I think that with problem 1 fixed, one could build by installing Sphinx site-wide, but I'd like to follow the sensible advice in [section 6.3](https://devguide.python.org/docquality/#helping-with-the-developer-s-guide), and use a virtual environment.

I'll propose you a fix in due course, as much like the Unix Makefile as I can.

**Comment by zware** [comment]
Have a look at what [Doc/make.bat](https://github.com/python/cpython/blob/master/Doc/make.bat) does, I think it's in better shape than this make.bat is at this point.

**Comment by jeff5** [comment]
@zware Thanks. There are some interesting things there, but not the use of a virtual environment.

I'm aiming for as much like the Makefile as possible and otherwise minimum change. (`.bat`s are so fragile.)

I take the hint from [this conditional](https://github.com/python/cpython/blob/db50ba7c72bd5f0617c50df3f1a1bb8b26955882/Doc/make.bat#L9) however that if you've defined your own command in SPHINXBUILD we should butt out with our venv.

**Comment by zware** [comment]
Ah, you're right; we haven't added venv support to Doc/make.bat.  Sorry for the red herring :(

Yes, if SPHINXBUILD is set, we should assume the user knows what they're doing and just go with it.  Otherwise, I like your plan of trying to match Makefile's behavior as closely as possible.

**Comment by jeff5** [comment]
Resolved in #268.
