### ISSUE TITLE
Delete the FAQ

### ISSUE THREAD

**Issue by brettcannon** [python/devguide#27]
It's not necessary as it was written for a time where we used version control systems that aren't as widely used or documented at git. [All references](https://github.com/python/devguide/search?utf8=%E2%9C%93&q=faq) should also be removed.

**Comment by willingc** [comment]
A suggested workplan to address this issue:

1. Verify that any useful content (esp. section [29.1 Communications](http://cpython-devguide.readthedocs.io/en/latest/faq.html#communications)) is found elsewhere in the devguide. If not, migrate that content to an appropriate devguide section.
- [ ] 29.1 Communication
- [ ] 29.2 Version control
- [ ] 29.3 SSH
- [ ] 29.4 General

2. Remove all FAQ content and references to the FAQ.

**Comment by brettcannon** [comment]
I don't think we should document version control stuff outside of our workflow as there's enough content on git online, so I say just drop that section. The same I think goes for SSH.

**Comment by Mariatta** [comment]
Is the FAQ ready to be removed? I can prepare a PR 😃

**Comment by brettcannon** [comment]
Someone should go through the FAQ to see if there's any relevant info in there that isn't either easily/better found elsewhere online or that is replicated in the proper place somewhere else in the devguide. So I don't know if it's ready yet until that's occurred.

**Comment by willingc** [comment]
@Mariatta If you have time to go through the FAQ, that would be awesome. Thanks!

**Comment by brettcannon** [comment]
Yes, if that wasn't clear, it's open to anyone to try and tackle. 😄 (long list of todos today that I'm trying to rush through)

**Comment by ezio-melotti** [comment]
A bit late to the party, but just yesterday I was looking for faq.rst and then accidentally came across this issue.
I think removing it was a bad idea, and just by reading the diff I got answers to a few questions I had that are currently not covered in the devguide.

I also disagree with the rationale:
`It's not necessary as it was written for a time where we used version control systems that aren't as widely used or documented at git.`

Even though I was familiar with HG (I wrote several of those FAQs myself), I often went back to them to look up the exact list of commands I needed to solve a particular problem.  While it's true that the same answers can be found online, there are several possible workflows and variations that need to be adapted to our workflow and repo structure.  The commands in the FAQ were easy to find and copy/paste.

**Comment by brettcannon** [comment]
I think the general feeling has been that instead of a FAQ we should have a doc(s) that cover scenarios and include the appropriate instructions. So that would mean if you were looking for something and it wasn't in the relevant doc that covered that scenario then that doc needs an update instead of a random entry in an FAQ.

**Comment by ezio-melotti** [comment]
This works for me as long as the commands are documented and easy to find.  You could argue that each scenario answer a specific question though :)
