### ISSUE TITLE
26.3. Abstract Syntax Trees (AST) - yield expression should be optional.

### ISSUE THREAD

**Issue by svelankar** [python/devguide#271]
In the python ASDL example , Yield expression should be optional.

**Comment by terryjreedy** [comment]
Open an issue of bugs.python.org.  PRs are for code patches, nearly always in response to a bpo issue, not for bug reports.

**Comment by svelankar** [comment]
The last time i had opened a bug for  devguide  issue on bugs.python.org (issue 31023) , i was told not to open a bug on bugs.python.org but a file a ticket here. Am i missing anything ?

**Comment by ezio-melotti** [comment]
I assume that you are reporting an issue about the example at https://devguide.python.org/compiler/#abstract-syntax-trees-ast and that this issue is related to #272 so this is the right place.

**Comment by terryjreedy** [comment]
Sorry, there is a separate issue tracker on git for the devguide repository.
