### ISSUE TITLE
Mention that backport can happen automatically

### ISSUE THREAD

**Issue by Mariatta** [python/devguide#281]
In this section: https://devguide.python.org/committing/#backporting-changes-to-an-older-version, it can mention that miss-islington will first try to do the backport automatically. In case that miss-islington is unable to do it, then the PR author or the core dev who merge it should look into backporting it themselves.

**Comment by Mariatta** [comment]
This has been addressed in #287. Thanks @blossomica for the PR :)

**Comment by blossomica** [comment]
You are welcome, @Mariatta ! It's an honour!
