### ISSUE TITLE
Update buildslave.rst page for Buildbot 0.9.x

### ISSUE THREAD

**Issue by zware** [python/devguide#290]
In part, the whole page needs `s/slave/worker/g`; any links to the master page will be wrong, and there may be other updates necessary as well.

**Comment by levlaz** [comment]
@zware I would love to tackle this issue. 

I ran `linkcheck`, and focused on the buildbot specific links. 

```
buildbots.rst:48: [broken] http://buildbot.python.org/all/#/console: Anchor '/console' not found
buildbots.rst:209: [broken] http://buildbot.python.org/all/waterfall?category=custom.stable&category=custom.unstable: 404 Client Error: Not Found for url: http://buildbot.python.org/all/waterfall?category=custom.stable&category=custom.unstable
buildslave.rst:26: [broken] http://buildbot.python.org/all/buildslaves: 404 Client Error: Not Found for url: http://buildbot.python.org/all/buildslaves
buildslave.rst:188: [broken] http://buildbot.python.org/all/buildslaves: 404 Client Error: Not Found for url: http://buildbot.python.org/all/buildslaves
buildslave.rst:202: [broken] http://docs.buildbot.net/current/manual/cfg-buildslaves.html#latent-buildslaves: Anchor 'latent-buildslaves' not found
```

I can go through and update all of these references, as well as updating the documentation itself for `s/slave/worker/g`. 

I would also like to rename the file itself to `buildworker.rst` if that is alright with you. 

Assuming this is all good, PR incoming in the next day or two.

**Comment by zware** [comment]
All of those updates sound good.  Let me know if you have trouble finding a link that `linkcheck` likes on buildbot.python.org; we can try adding redirects if needed.

Any other things that look out of date for Buildbot 0.9.x as you're making those changes, please feel free to fix.  I haven't had a chance to look through the page again myself to point out anything else in particular.

I look forward to reviewing your PR :)

**Comment by zware** [comment]
Thanks @levlaz!
