### ISSUE TITLE
Add linkcheck to CI

### ISSUE THREAD

**Issue by levlaz** [python/devguide#292]
I noticed a TODO in the [.travis.yml](https://github.com/python/devguide/blob/master/.travis.yml#L8) file to add linkcheck to CI. 

This is simple enough to do, is there a historical reason why it has not been done?

**Comment by zware** [comment]
I suspect it's just the fact that it would be failing, or take significant time to run.  It would be worth a PR to turn it on and see what it does, but there's no guarantee that we'd merge it yet.

**Comment by levlaz** [comment]
It might be useful to run the report on each build (and not cause the build to "fail") and save it as an artifact for handy reference. 

It seems that in order to use artifacts on travis you need to [upload them to S3 manually](https://docs.travis-ci.com/user/uploading-artifacts/). Which seems not ideal. 

Would you be opposed to switching to CircleCI? They host artifacts for free. 

Disclaimer: I work at CircleCI. :)

**Comment by willingc** [comment]
Next action: Enable linkcheck on travis as a test. Mark this test as Failure OK so that it does not prevent merges yet provides information to contributors.

**Comment by hugovk** [comment]
Please see PR #369.
