### ISSUE TITLE
Broken link to Copyright page.

### ISSUE THREAD

**Issue by Mariatta** [python/devguide#299]
At the very bottom of https://devguide.python.org, there is a copyright link. That link is 404.

**Comment by Mariatta** [comment]
I wonder if the link should be removed, so it becomes a regular text?
Otherwise, which page should it point to?

**Comment by brettcannon** [comment]
I have no idea what it ever pointed at, nor why it would need to point to anything. I guess ask @VanL , otherwise just make it plain text.

**Comment by Mariatta** [comment]
I'm just gonna make it into plain text. :)

**Comment by ezio-melotti** [comment]
Maybe the template was copied from docs.python.org: https://docs.python.org/3/copyright.html

**Comment by Mariatta** [comment]
Oh hmm .. Ok then maybe best to ask @VanL about this...

**Comment by MarkMangoba** [comment]
I just e-mailed @VanL about this.  Plain text is just fine if we don't hear back within 2 days, that is how it is via python.org.

**Comment by Mariatta** [comment]
Thanks @MarkMangoba :)

**Comment by Mariatta** [comment]
Since there hasn't been any updates, I'm committing the change to make it plain text :)
