### ISSUE TITLE
Keeping github branch in sync with master

### ISSUE THREAD

**Issue by willingc** [python/devguide#30]
The `github` branch is no longer in sync with `master`.

Currently, the `github` branch is `This branch is 3 commits ahead, 4 commits behind master.` Contributors, unless they are core devs with privileges to push to `master`, are working with out of date code. 

I recommend that we find a way to automate keeping the github branch ahead or even with master.

**Comment by brettcannon** [comment]
Beyond occasionally creating a PR manually to merge across the branches, you are talking about solving one of the great issues in version control. :) Solve this and you may have solved it for CPython backporting fixes.

**Comment by willingc** [comment]
Closing as resolved since I was the original issue creator.
