### ISSUE TITLE
Firefox Search Engine plugin link returns 404 error

### ISSUE THREAD

**Issue by CuriousLearner** [python/devguide#306]
Under the key resources section: 
https://devguide.python.org/#key-resources

Link to `Firefox search engine plug-in` pointing to https://www.python.org/dev/searchplugin/ appears to be broken.

**Comment by brettcannon** [comment]
Probably should just remove the reference.

**Comment by CuriousLearner** [comment]
@brettcannon Fixed that in the PR.

**Comment by ezio-melotti** [comment]
Fixed, thanks for the report and the PR!

@brettcannon do you remember what this plugin was?
