### ISSUE TITLE
Document how to make `apt-get build-dep python3.5` to work

### ISSUE THREAD

**Issue by brettcannon** [python/devguide#32]
I.e. if you get the error about needing to update `sources.list`, then point out how to do that.

**Comment by brettcannon** [comment]
http://askubuntu.com/questions/496549/error-you-must-put-some-source-uris-in-your-sources-list, although on 14.04 I just copied the three lines I had and then changed `deb` to `deb-src`.

**Comment by warsaw** [comment]
I don't see a diff, but that should pretty much work.

**Comment by brettcannon** [comment]
@warsaw you "don't see a diff" as in you "don't see a diff file", or you "don't see a difference"? If it's the former it's because I just didn't have the time to do a PR. If it's the latter, not sure what you mean other than maybe not explaining exactly and instead just linking to the askubuntu.com link?

**Comment by DimitrisJim** [comment]
Just bumped into this myself on `16.04` and had to comment out a couple of `deb-src`s. Would adding a url to  the question on ask-ubuntu suffice? Or would a simple line of the form "Back up your `/etc/apt/sources.list` and then uncomment the `deb_src` lines" do the trick?

**Comment by brettcannon** [comment]
Depends on how easy it is for that question to becomes outdated in the future. If it's easy then listing the individual steps would be good, but if the answer is stable then linking to it should suffice.

**Comment by lulouie** [comment]
I just encounter the same problem today on `17.04`, and the error says that must update `source.list`. And resolve by manually install all dependency files. (the method list here isn't quite easy to found at Internet...)
