### ISSUE TITLE
Propose change to new user link for documentation issues on the bug tracker

### ISSUE THREAD

**Issue by csabella** [python/devguide#321]
On the devguide landing page, there's a section called 'Contributing', under which there is a section and links:
```
Beginner tasks to become familiar with the development process

        Helping with Documentation
        Increase Test Coverage
```

Clicking on 'Helping with Documentation' leads to the page of the same name and section 6.1 starts with:
```
6.1. Helping with issues filed on the issue tracker

If you look at documentation issues on the issue tracker, you will find various documentation problems that need work. Issues vary from typos, to unclear documentation, to something completely lacking documentation.
```
Within that text 'documentation issues' is also a link, leading to this page:
[current](
https://bugs.python.org/issue?%40search_text=&ignore=file%3Acontent&title=&%40columns=title&id=&%40columns=id&stage=&creation=&creator=&activity=&%40columns=activity&%40sort=activity&actor=&nosy=&type=&components=4&versions=&dependencies=&assignee=&keywords=&priority=&%40group=priority&status=1&%40columns=status&resolution=&nosy_count=&message_count=&%40pagesize=50&%40startwith=0&%40queryname=&%40old-queryname=&%40action=search)

When I first looked at the devguide last year to try to begin contributing, I found the results returned from that link very confusing.  They are in priority sections with the oldest ones first.  I didn't know if I was looking at the right thing because I wasn't familiar with the bug tracker and I didn't understand that there are some issues that can be 7+ years old.  Anyway, I propose the following link to make it easier for new users to find documentation bugs to work on:
[suggested](
https://bugs.python.org/issue?%40search_text=&ignore=file%3Acontent&title=&%40columns=title&id=&%40columns=id&stage=&creation=&creator=&activity=&%40columns=activity&%40sort=activity&actor=&nosy=&type=&components=4&versions=&dependencies=&assignee=&keywords=6&priority=&status=1&%40columns=status&resolution=&nosy_count=&message_count=&%40group=&%40pagesize=100&%40startwith=0&%40sortdir=on&%40queryname=&%40old-queryname=&%40action=search)

Also, I think it might be helpful in that section to add a sentence to explain that some issues already have a pull request or patch that indicates that someone else is already working on the issue.

**Comment by ezio-melotti** [comment]
+1

**Comment by ncoghlan** [comment]
Both of those suggestions make sense to me as well - the paperclip and octocat icons are handy, but thoroughly cryptic if nobody has told you what they mean :)

**Comment by csabella** [comment]
Thanks, I'll prepare a PR.

**Comment by ncoghlan** [comment]
Thanks @csabella!
