### ISSUE TITLE
Mention that building Python docs now requires blurb

### ISSUE THREAD

**Issue by Mariatta** [python/devguide#323]
This section describes how to build the docs: https://devguide.python.org/documenting/#building-the-documentation

It currently mentions that we need to have sphinx installed. However, I noticed that `blurb` is now needed for building the docs.

`make html` will fail if we don't have `blurb` installed.

The documentation should be updated with the instruction to install `blurb` too.

**Comment by matrixise** [comment]
I have read the code of Doc/Makefile, and we install blurb when we create the venv, https://github.com/python/cpython/blob/master/Doc/Makefile 

Do we need to update the documentation ?

**Comment by Mariatta** [comment]
Hmm maybe something wrong with my computer setup?

I did make html from the Doc directory and it does not work. Here's the output from my terminal:

```
$ make -C Doc html
mkdir -p build
Building NEWS from Misc/NEWS.d with blurb
/bin/sh: blurb: command not found
make: *** [build] Error 127
$ cd Doc
$ make html
mkdir -p build
Building NEWS from Misc/NEWS.d with blurb
/bin/sh: blurb: command not found
make: *** [build] Error 127
$
```

Once I manually created the venv and installed sphinx and blurb, then it works.

**Comment by Mariatta** [comment]
The paragraph says: "You are expected to have installed the latest stable version of Sphinx on your system or in a virtualenv, so that the Makefile can find the sphinx-build command. You can also specify the location of sphinx-build with the SPHINXBUILD make variable."

So it should mention about adding blurb in addition to sphinx, I think.

**Comment by JulienPalard** [comment]
I would go for something like:

> You are expected to have installed the latest stable version of Sphinx and blurb on your system or in a venv, so that the Makefile can find the sphinx-build command. You can also specify the location of sphinx-build with the SPHINXBUILD make variable.

**Comment by bukun** [comment]
``blurb`` could be installed via pip.

    pip3 install blurb
