### ISSUE TITLE
Dino Viehland's email address seems incorrect (in motivations page)

### ISSUE THREAD

**Issue by Mariatta** [python/devguide#343]
@DinoV I noticed your email address listed is Antoine's.
Do you want to update that to the right email address, or simply remove that field from your entry?

https://github.com/python/devguide/blob/b1e7450b7aed15cfe975b78a324a45eaedc14125/motivations.rst#L240-L243

Thanks.

**Comment by DinoV** [comment]
Woops, thank you, I've fixed it!
