### ISSUE TITLE
Migrate devguide to python-docs-theme

### ISSUE THREAD

**Issue by willingc** [python/devguide#351]
For maintainability and consistency, migrating to https://github.com/python/python-docs-theme makes good sense.

fyi @ned-deily @jonparrott

**Comment by zware** [comment]
We did lose our explicitly-different-from-docs.python.org top bar color.

**Comment by Mariatta** [comment]
Sorry I missed that :(
@jonparrott is the top bar color something can be configured for devguide? Thanks.

**Comment by zware** [comment]
[#6BA81E](https://github.com/python/devguide/pull/355/files#diff-3e74b5eaf1c4be4469edfd3ae84931d8L15)

I'm not sure whether we also had to change text colors to go along with that.

**Comment by willingc** [comment]
We should be able to set custom.css in the devguide to adjust colors as needed. Thanks @jonparrott. Please let me know if you hit a snag.
