### ISSUE TITLE
Dev Guide Get Started Guide 

### ISSUE THREAD

**Issue by Mariatta** [python/devguide#36]
I found that the Get Started document here https://docs.python.org/devguide/ to be not very effective way for me to get started.

The page started by saying, "here are the basic steps":
1.  check out source code
2. compile
3. run tests
4. make patch
5. submit to issue tracker

I agree that these five steps correctly describe the full cycle of contributing to the code base.
**However**, to really get started for the *first time ever*, it's not gonna work. In realty, there is a step 0, and that is to Get Setup ( https://docs.python.org/devguide/setup.html#setup)

Can I suggest that Get Setup be clearly explicitly described as step 0 or step 1 of contributing? At the moment it is only subtly mentioned under the Get Started heading as a link. At first I missed this link completely, and it caused some frustration on my part.

As a first timer, I tried jumping on doing step 1 right away, (checkout out source code), but then I realized I don't have mercurial installed. I had to do some googling on how to install mercurial. Finally managed to check out the source code using the `hg clone`. Only much later that I came across the Get Setup page.

After I installed mercurial and checked out source code, I read the instruction on step 2, to compile python.
Foolishly, I tried to execute the command `/configure --with-pydebug && make -j2` 
Well that didn't work at all. I almost gave up with contributing because of failing to complete step 2. 
Again, I had to go back and read the Get Setup page more thorough explanation on how to compile, and it turns out for my machine (mac os) I needed a different command, whereas the get started guide says I could use that command above.

I discussed this with @gvanrossum earlier today, and he suggested that I file a bug or an issue about this matter.
Guido also pointed out that the --with-pydebug flag is for advanced debugger. and preferably it is separated into two lines

Getting local environment is the first step before anyone can begin contributing. It would really be great if this page could be improved and updated to be more beginner friendly. 

Thanks, and sorry if this is a long ticket. Let me know if anyone has further thoughts on how to improve this page. I'd be happy to help out however I can.

**Comment by gvanrossum** [comment]
Thanks for persevering Mariatta! If you want to you can submit a PR with changes to the devguide that would have helped you. Any one of us will then be able to review and merge that change! (Hopefully getting started with the devguide is simpler than getting started with Python. :-)

**Comment by willingc** [comment]
@mariatta Feel free to ask question about Sphinx or how to build the devguide here if needed too :-)

**Comment by Mariatta** [comment]
Thanks, I made pull request for this. Would appreciate any feedback 😃

**Comment by ncoghlan** [comment]
I merged the initial PR, which can be seen at http://cpython-devguide.readthedocs.io/en/latest/ (the main site will also update automatically, but that's currently time based rather than per commit).

If there's anything else you'd like to tweak in that section (or elsewhere in the dev guide), feel free to send additional PRs.

I think you've addressed the concerns you raised above, though, so I'm going to close the issue itself.
