### ISSUE TITLE
sorry for yet another self discussion

### ISSUE THREAD

**Issue by stevexyz** [python/devguide#361]
Yes I know, "self" parameter have been discussed a lot, but still I didn't find this proposal. If it was instead take my sincere apologies and close the issue.

The disturbing part of the "self" parameter is the "asymmetry" of definition and call. So I was thinking: why not do define methods like: ``def self.whatevermethod(par1, par2, etc)`` instead of ``def whatevermethod(self, par1, par2, etc)``?

This will allow the call and the definition to be written exactly in the same way, still leaving the "clarity" of the additional input for the function. Moreover this can be made backward compatible (even still without making self a reserved word).

I've been short by purpose but ready to elaborate if needed. Thank you for the attention.

**Comment by JulienPalard** [comment]
Hi @stevexyz, and welcome.

It's the wrong place for this subject, this repository is about the "contributing to Python guide", not the evolution of the language. The right place to speak about your idea is the [python-ideas mailing list](https://mail.python.org/mailman/listinfo/python-ideas).

It has already been discussed here: https://mail.python.org/pipermail/python-ideas/2007-November/001194.html so please read the thread before posting in case it already have a clear answer for you.
