### ISSUE TITLE
OpenHatch on Getting Started page

### ISSUE THREAD

**Issue by csabella** [python/devguide#374]
The [Getting Started](https://devguide.python.org/setup/) page mentions OpenHatch in the second paragraph, but OpenHatch's step 1.4 is about Mercurial instead of git.  I've filed a bug [there](https://github.com/openhatch/oh-mainline/issues/1814), but not sure if anyone is maintaining it?  

Anyway, not sure if the devguide should be updated or if anyone had suggestions for updating OpenHatch.

Thanks!

**Comment by brettcannon** [comment]
We should drop the OpenHatch link since that page has not been updated since 2014.

**Comment by Mariatta** [comment]
Closed via #375
