### ISSUE TITLE
GitHub quick edit through web UI not working?

### ISSUE THREAD

**Issue by nascheme** [python/devguide#382]
https://devguide.python.org/committing/#working-with-git
```quote
An exception to this rule: you can make a quick edit through the web UI of
GitHub, in which case the branch you create can exist for less than 24 hours.
This exception should not be abused and be left only for very simple changes.
```

I tried to use this for a simple wording change in the docs.  It doesn't seem to work as 'master' is a protected branch.  I think the devguide should provide a more clear explanation of the steps (in case you can actually do these trivial edits) or we should remove that section.

**Comment by Mariatta** [comment]
You can make edits through web UI, but you can't make it directly to master. You'll still need to create the branch and go through PR process.

**Comment by nascheme** [comment]
Okay, I guess the issue is mostly with me not reading carefully enough and having a different expectation.  I expected to make a trivial fix without making a branch and without going through the PR process.
