### ISSUE TITLE
Add on new section about Translations  to 7. Documenting Python

### ISSUE THREAD

**Issue by willingc** [python/devguide#389]
> There are now several official translations: see current doc pages, the bottom of https://devguide.python.org/experts/, and https://www.python.org/dev/peps/pep-0545/.  According to the pep, discussion is on doc-sig.  https://mail.python.org/mailman/listinfo/doc-sig

> 'third party' is not quite right, but there is no 'separate repository and issues tracker' selection.

> Carol, perhaps devguide 7. Documenting Python should have a short new section 7.6 Translations with at least the above info, better formatted.

See original message from bpo https://bugs.python.org/issue24978#msg319774

**Comment by devarshigoswami** [comment]
If this hasn't been handled, Can I work on it?

**Comment by za** [comment]
Maybe we can also close this issue cc: @ezio-melotti .
