### ISSUE TITLE
Go through devguide file-by-file for GitHub migration

### ISSUE THREAD

**Issue by brettcannon** [python/devguide#39]
We need to go through the entire devguide for the GitHub migration. Having a module marked off as done means that it is ready to go in the `github` branch or a separate issue to track what needs to be done for a page has been created. The key point is that once every page is checked off there will be a clear understanding of what is left to do for the GitHub migration.

- [ ] `committing.rst` (#44)
- [ ] `coredev.rst` (#45)
- [ ] `devcycle.rst` (#46)
- [ ] `developers.rst` (#47)
- [ ] `faq.rst` (#27, #48)
- [ ] `gitdevs.rst` (#49)
- [ ] `index.rst` (#50)
- [ ] `patch.rst` (#51)
- [ ] `setup.rst` (#52)
- [ ] `triaging.rst` (#53)
- [x] `buildbots.rst`
- [x] `buildslave.rst`
- [x] `clang.rst`
- [x] `communication.rst`
- [x] `compiler.rst`
- [x] `coverage.rst`
- [x] `coverity.rst`
- [x] `docquality.rst`
- [x] `documenting.rst`
- [x] `experts.rst`
- [x] `fixingissues.rst`
- [x] `gdb.rst`
- [x] `grammar.rst`
- [x] `help.rst`
- [x] `langchanges.rst`
- [x] `motivations.rst`
- [x] `runtests.rst`
- [x] `silencewarnings.rst`
- [x] `stdlibchanges.rst`
- [x] `tracker.rst`

**Comment by brettcannon** [comment]
Now that there are separate issues for the remaining pages, the GitHub milestone can be used to track what's left to do.

**Comment by Mariatta** [comment]
Do you want to check off these issues? Since they're closed already...
#44 #45 #47 #48 #49 #50 #51 #52 #53

#46 seems to be closed, but you mentioned about needing to make another PR.
