### ISSUE TITLE
Migrate over issues from bugs.python.org

### ISSUE THREAD

**Issue by brettcannon** [python/devguide#4]
- [x] Create duplicate issues from the [`Devguide` component](http://bugs.python.org/issue?%40search_text=&ignore=file%3Acontent&title=&%40columns=title&id=&%40columns=id&stage=&creation=&creator=&activity=&%40columns=activity&%40sort=activity&actor=&nosy=&type=&components=26&versions=&dependencies=&assignee=&keywords=&priority=&status=1&%40columns=status&resolution=&nosy_count=&message_count=&%40group=&%40pagesize=50&%40startwith=0&%40sortdir=on&%40queryname=&%40old-queryname=&%40action=search)
- [x] Delete the `Devguide` component (#26)

**Comment by brettcannon** [comment]
Component was `26,7047:18982,,,Devguide,2.5`

**Comment by willingc** [comment]
@brettcannon Thanks! This is looking great :tada:
