### ISSUE TITLE
Add an appendix to the index page

### ISSUE THREAD

**Issue by brettcannon** [python/devguide#40]
Stuff that is not part of what a normal person will care about can go in there, e.g. details about the compiler or how to update the grammar.

**Comment by willingc** [comment]
@brettcannon Do you wish to close this or perhaps clarify further? I'm not sure what you mean by appendix and what content it would hold.

**Comment by willingc** [comment]
@brettcannon #354 seems to have taken a reasonable first step on addressing this. I'm going to close this issue. We can always add new issues with specific action items. 👍
