### ISSUE TITLE
Invalid git clone path.

### ISSUE THREAD

**Issue by undali** [python/devguide#405]
There is an invalid git clone path in the front page of https://devguide.python.org/.  It says to do clone using `git clone https://github.com/<your_username>/cpython` . But it should be `git clone https://github.com/python/cpython.git`.

Another one is at https://devguide.python.org/docquality/ asked to clone `git clone https://github.com/<your_username>/devguide`

I want to fix it.

**Comment by Mariatta** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/python/devguide/issues/61 (devguide-git bot), https://github.com/python/devguide/issues/130 (Preferred cloning URL), https://github.com/python/devguide/issues/18 (Document how to commit using git), https://github.com/python/core-workflow/issues/69 (Add argument for cpython clone), and https://github.com/python/core-workflow/issues/186 (blurb: get rid of spaces in paths).

**Comment by undali** [comment]
I was wrong. It says to fork the repo first. Then the path is fine.
