### ISSUE TITLE
Mention of Mercurial instead of GitHub

### ISSUE THREAD

**Issue by lysnikolaou** [python/devguide#423]
In the Continuous Integration part there is the following: 

> when a new change is pushed to this branch on the public Mercurial repository

Shouldn't this be updated to mention Github instead?

**Comment by Mariatta** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/python/devguide/issues/17 (Remove mentions of Mercurial), https://github.com/python/core-workflow/issues/20 (Backup GitHub information), https://github.com/python/core-workflow/issues/32 (Add the mention bot?), https://github.com/python/devguide/issues/186 (Clarify how to review on GitHub), and https://github.com/python/core-workflow/issues/80 (Move Codecov configuration under .github).

**Comment by lysnikolaou** [comment]
I will try to submit a PR ASAP.
