### ISSUE TITLE
Add a mention to the correct workflow for WSL users building for Windows

### ISSUE THREAD

**Issue by augustogoulart** [python/devguide#425]
When using the Windows Subsystem for Linux (WSL), if you git clone the project via Linux and tries to compile the project on Windows, Visual Studio will be able to see the project, but won't be able to compile the included files.
Since this is not a bug, I believe it would be nice to mention the correct workflow.

![screenshot 2](https://user-images.githubusercontent.com/13952931/46898014-8ea08e00-ce5c-11e8-92b0-bf6cc806d7d1.png)

**Comment by taleinat** [comment]
@Mariatta

> GitMate.io thinks possibly related issues are python/core-workflow#32 (Add the mention bot?), #202 (Mention core-workflow mailing list / repo), #54 (Streamline workflow), python/core-workflow#74 (Add bpo link to mention-bot when issue id provide), and #3 (Add Travis support).

Unfortunately, none of those is relevant.

**Comment by taleinat** [comment]
I've reproduced this with the following steps:

1. In an Ubuntu WSL shell: `git clone --depth=1 https://github.com/python/cpython.git cpython_wsl_test`
2. In a `cmd.exe` shell:
2.1 `cd cpython_wsl_test`
2.2 `PCbuild\build.bat`

I get the same errors reported by @augustogoulart.

(Win10 Pro 64-bit with Ubuntu 18.04 64-bit in WSL)

**Comment by taleinat** [comment]
@willingc, the current suggested resolution is "this doesn't work, don't do it!", adding a note to this effect to the dev guide.

**Comment by taleinat** [comment]
@zware, could it be different git `autocrlf` settings perhaps? Or something similar?

**Comment by zware** [comment]
Sorry I've been blocking this and haven't gotten back to it yet!  However, I still can't reproduce the issue.  It's possible that my Windows (10.0.16399.665), WSL distribution (Ubuntu 16.04.4), or git (2.7.4) are significantly older than what you're using, but the whole issue doesn't make sense to me.  When git checks out the files, they're just files on disk and the build system doesn't look for or care about Git (except to set variables for the version string, but any errors there are silenced and ignored).  Can you confirm that the checkout is actually complete, and the files do appear to be where they should be?

I suppose it's possible that `autocrlf` is causing issues; I don't have it set at all and rely on `.gitattributes` instead.

Are you making your checkout within the Linux filesystem, or the Windows filesystem (/mnt/c/)?

**Comment by augustogoulart** [comment]
@zware these are the steps I'm following to reproduce the error.

Windows 10.0.17134 build 17143, WSL Debian 9 (stretch) and git 2.11 installed on Linux, and git 2.19.1.windows.1 on Windows. Compiler Microsoft (R) C/C++ Optimizing Compiler Version 19.15.26730.

Checkout withing Linux. path: `/mnt/c/Users/augus/Workspace`

![image](https://user-images.githubusercontent.com/13952931/47602821-315b1f80-d9ba-11e8-95d3-74b652fc4940.png)

Compiling on Windows. Fails because Visual Studio can not find the files:

![image](https://user-images.githubusercontent.com/13952931/47602894-2fde2700-d9bb-11e8-9202-6720d3a34c82.png)

Checking each file path, the file exists:

![image](https://user-images.githubusercontent.com/13952931/47603006-73856080-d9bc-11e8-9ce8-8129cc50dca3.png)

**Comment by JulienPalard** [comment]
Can this be a permission issue? Not familiar with Windows permissions though.
