### ISSUE TITLE
accessing google search

### ISSUE THREAD

**Issue by parikannappan** [python/devguide#429]
how can a do a google search sing python code ?

**Comment by encukou** [comment]
Hi,
This repository is a guide on how to contribute *to* Python. It is the wrong place for your question.
Try a mailing list like [tutor](https://mail.python.org/mailman/listinfo/tutor) instead, preferably after looking at documentation of [Python](http://docs.python-requests.org/en/master/user/quickstart/) or [Requests](http://docs.python-requests.org/en/master/).
