### ISSUE TITLE
Include info from Victor's "Build CPython on Windows"

### ISSUE THREAD

**Issue by ned-deily** [python/devguide#433]
We should consider including the info in @vstinner 's quick guide to building Python on Windows into the "Getting Started" chapter of the devguide.

https://cpython-core-tutorial.readthedocs.io/en/latest/build_cpython_windows.html

**Comment by Mariatta** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/python/devguide/issues/267 (Cannot build devguide in virtual environment on Windows), https://github.com/python/devguide/issues/90 (Windows build instructions out-dated/unclear for 2.7 branch), https://github.com/python/core-workflow/issues/113 (Questions about cherry-picker from Windows never-venv user), https://github.com/python/core-workflow/issues/46 (Drop the gcc build from Travis), and https://github.com/python/devguide/issues/172 (Add PDF build).
