### ISSUE TITLE
Update coredev.rst for Git/GitHub

### ISSUE THREAD

**Issue by brettcannon** [python/devguide#45]

**Comment by matrixise** [comment]
@brettcannon where is the repo of https://hg.python.org/committers.txt ? because I think there is no Git repo for this file and I would like to update this file.

**Comment by brettcannon** [comment]
@matrixise there is no repository for that file as it's auto-generated from the registered SSH keys of committers.

**Comment by matrixise** [comment]
@brettcannon ok, in this case, I won't change this part in the coderev.rst file.

**Comment by ncoghlan** [comment]
I believe the GitHub equivalent would be to pull the list of "Python Core" team members from https://github.com/orgs/python/teams/python-core

**Comment by brettcannon** [comment]
@ncoghlan it is but I don't think that list is public.

**Comment by ncoghlan** [comment]
@brettcannon OK, in that case it probably makes sense to assume that `committers.txt` will stick around in some form as a public export generated from the team list.

**Comment by brettcannon** [comment]
@ncoghlan what do we even need the list for? GitHub clearly delineates who is a Python team member in code reviews and bugs.python.org does as well, so it isn't to call out who is or is not a core dev.

**Comment by ncoghlan** [comment]
Sorry, I was assuming we used it somewhere based on @matrixise's comment above. If we can get rid of it entirely, so much the better :)

**Comment by matrixise** [comment]
in fact, https://github.com/orgs/python/teams/python-core is not public because I get a 404 when I try to access to the page.
