### ISSUE TITLE
Setup guide should link to platform readme (macOS)

### ISSUE THREAD

**Issue by jaraco** [python/devguide#453]
Today I was reading the devguide to try to understand how framework builds work, but found it inadequate. I later learned that the Mac/README file in the repo has more detail. The devguide should reference that in `setup/#macos`. Filing this ticket so I don't forget.

**Comment by Mariatta** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/python/core-workflow/issues/30 (Link to developer guide in CPython repo description), https://github.com/python/devguide/issues/230 (Add a reference link to the "Python Extension Patterns" guide?), https://github.com/python/core-workflow/issues/224 (Double link to the same PR), https://github.com/python/devguide/issues/124 (Github organization link is secret and not accessible from core-dev guide), and https://github.com/python/devguide/issues/221 (broken links and 404).

**Comment by terryjreedy** [comment]
Ned Deily has acknowledged that the current information about building Python on Mac is obsolete and inadequate.  (For instance, tcl/tk is now included, and only 64 bit should be built for 3.7+.) But he has not yet updated it.  Before linking the readme, I think he should be asked if the more detail is accurate.
