### ISSUE TITLE
No entry for  Jason R. Coombs in developers.rst

### ISSUE THREAD

**Issue by matrixise** [python/devguide#455]
Hi,

I can see that Jason is a core-dev but I don't find any entry in developers.rst.

Thank you

**Comment by Mariatta** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/python/devguide/issues/47 (Update developers.rst for Git/GitHub), https://github.com/python/devguide/issues/170 (Who is BCP at developers.rst), and https://github.com/python/devguide/issues/417 (Imprecision in compiler.rst).
