### ISSUE TITLE
Link to meta tracker broken

### ISSUE THREAD

**Issue by jaraco** [python/devguide#456]
In the guide, there is a [section about the meta tracker](https://devguide.python.org/tracker/#the-meta-tracker) which links to [this site](http://psf.upfronthosting.co.za/roundup/meta/), which appears to be non-functional (it's a blank page to me). The tracker itself links to [this site](https://github.com/python/psf-infra-meta). Is that the correct meta tracker?

**Comment by Mariatta** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/python/devguide/issues/299 (Broken link to Copyright page.), https://github.com/python/devguide/issues/221 (broken links and 404), https://github.com/python/core-workflow/issues/54 (Travis tests are broken), https://github.com/python/devguide/issues/321 (Propose change to new user link for documentation issues on the bug tracker), and https://github.com/python/core-workflow/issues/224 (Double link to the same PR).

**Comment by Mariatta** [comment]
I think it should be this url now? https://github.com/python/bugs.python.org

**Comment by terryjreedy** [comment]
Something needs to be cleared up.  The psf_infra_meta is much older (June 2017) and is not limited to the bugs.python.org, in spite of what readme.md says.  The bugs.python.org tracker is specific and has more issues.  It starts with https://github.com/python/bugs.python.org/issues/1 about migrating open issues from the old tracker.  I added a comment there about making b.p.o, devguide, and psf-infra-meta consistent.

**Comment by ezio-melotti** [comment]
The section about the meta tracker is now gone, so this can be closed.
