### ISSUE TITLE
Update devcycle.rst for Git/GitHub

### ISSUE THREAD

**Issue by brettcannon** [python/devguide#46]

**Comment by matrixise** [comment]
check this PR: https://github.com/python/devguide/pull/67

**Comment by brettcannon** [comment]
I actually needed to clarify some wording on workflow changes so I needed to do my own PR.

**Comment by Mariatta** [comment]
> I actually needed to clarify some wording on workflow changes so I needed to do my own PR.

@brettcannon Do you want to keep the issue open? So we know that there's work pending still?

**Comment by brettcannon** [comment]
No, this can be closed as my PR should have covered everything.
