### ISSUE TITLE
Deploy pull request changes to Netlify so we can preview the devguide

### ISSUE THREAD

**Issue by Mariatta** [python/devguide#463]
Original thread in core-workflow mailing list:
https://mail.python.org/archives/list/core-workflow@python.org/thread/5FBBRHIWXWRCGHHKCU7WQR3MNFEX4647/

It would be great if we can have a preview of the docs on the internet (without having to manually build it ourselves locally). This is useful for reviewers who want to view the changed documentation.

Service like [netlify](https://www.netlify.com/) allows us to deploy the pull request changes for preview.

Before integrating this for docs.python.org, it would be great to try this out in devguide.

cc @matrixise

**Comment by Mariatta** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/python/devguide/issues/133 (Update Devguide about pull request commit documentation.), https://github.com/python/devguide/issues/104 (Should an issue be created first, before the Pull Request?), https://github.com/python/devguide/issues/215 (Editing pull request: Can we rebase instead of merge?), https://github.com/python/devguide/issues/325 (Add tricks for the Pull Requests review?), and https://github.com/python/core-workflow/issues/39 (checking code style for pull request).

**Comment by ewdurbin** [comment]
I believe this was successful for pypa/setuptools, as was setup back at PyCon 2018 sprints. Let me know if you need any assistance and I can try to recall what went into that process.

**Comment by Mariatta** [comment]
I think I got it setup? 😅
test PR #464 
https://deploy-preview-464--cpython-devguide.netlify.com/

But I had signed up using a personal account on netlify. Perhaps I should transfer this to you or to the PSF?

**Comment by ewdurbin** [comment]
I'm already acting as the Owner for pypa/setuptools with two other administrators.

Happy to accept the transfer and add your user as an Admin. If possible I'd love to recruit one other user for the role.

**Comment by Mariatta** [comment]
Sounds great! I tried looking into netlify and couldn't really figure out how to transfer or add other admins 😅 Let me know what to do here.

**Comment by willingc** [comment]
I'm happy to act as another Admin for the dev guide @Mariatta @ewdurbin unless there is someone else that wishes to do so. I already have the netlify toolchain on my system.

**Comment by matrixise** [comment]
@Mariatta I could work on this issue with the doc

**Comment by ewdurbin** [comment]
@Mariatta can you share what if any particular settings in netlify were needed to create the initial setup? I can go ahead and create a new project and add the new admins.

**Comment by Mariatta** [comment]
I went to netlify, and added python/devguide repo.
Then in the build settings:
Build command: `sphinx-build -n -W -q -b html -d _build/doctrees . _build/html`
Publish directory: `_build/html`
Branch: `master`.

I think that's all.

Under Build & deploy > Continuous Deployment > Deploy contexts, just ensure the Deploy previews: "Automatically build deploy previews for all pull requests" is selected (I think it was by default)

Thanks.

**Comment by willingc** [comment]
@Mariatta I'm going to close this since it seems to be working well.
