### ISSUE TITLE
Add a "Patterns" chapter

### ISSUE THREAD

**Issue by matrixise** [python/devguide#465]
Yesterday, I have fixed an issue in bpo and this issue was for the support of `os.PathLike` in `FileCookieJar`. Since the introduction of `os.PathLike` and `__fspath__`, we continue to convert some parts of code to be `os.PathLike` compliant and I think there is a pattern for that. 

Maybe we could create a page "Patterns" with some examples.

For example (but need to be tested and approved)

## How to support a `os.PathLike` object?
```python
def __init__(self, filename):
    try:
        filename = os.fspath(filename)
    except TypeError:
        raise ValueError("filename must be a string-like or path-like object")
```

**Comment by Mariatta** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/python/core-workflow/issues/189 (Add CONTRIBUTING.md), https://github.com/python/devguide/issues/3 (Add Travis support), https://github.com/python/devguide/issues/172 (Add PDF build), https://github.com/python/devguide/issues/136 (Add a chapter for introducing common function / class' corresponding source file), and https://github.com/python/core-workflow/issues/32 (Add the mention bot?).

**Comment by ncoghlan** [comment]
Why are we converting an accurate `TypeError` to an incorrect `ValueError`? (If the passed in object doesn't adhere to what `os.fspath` supports, change the *value* passed in won't help - you have to pass in an argument of a different type)

**Comment by matrixise** [comment]
@ncoghlan good catch

my example comes from `cookiejar` where there was a check and if there was an exception this one was catched and re-raised as a `ValueError`

I could fix it in `cookiejar` but I don't want to break the backward-compatiblity, or maybe I could document it in the whatsnew/38.html 

I am going to fix my PR with your recommendation in CPython: https://github.com/python/cpython/pull/11945/files#diff-e85eca61cec5281c45f14cd6819bf548L1766

Thank you

**Comment by matrixise** [comment]
Ok I have fixed my PR https://github.com/python/cpython/pull/11945

Thank you

**Comment by brettcannon** [comment]
I think this is out of scope for the devguide. Patterns like this are a general thing for the wider community and should be covered elsewhere, e.g. blog posts or the documentation.
