### ISSUE TITLE
Use the imperative form for the bullet list on the Continuous Integration page

### ISSUE THREAD

**Issue by csabella** [python/devguide#467]
Relevant section:
```
The build steps run by the buildbots are the following:

    Checkout of the source tree for the changeset which triggered the build
    Compiling Python
    Running the test suite using strenuous settings
    Cleaning up the build tree
```

**Comment by aditisingh2362** [comment]
Could you please explain the meaning of imperative form?

**Comment by csabella** [comment]
@aditisingh2362, the imperative form of a verb means that it's an action.  For example, `checkout` would be an action, but `checking out` would not.  This [link](https://blog.esllibrary.com/2018/01/23/imperative-verbs/) describes it a bit more and you can also google it for other descriptions.  Hope that helps.

**Comment by za** [comment]
Ping @willingc if you can close the issue. Thanks!
