### ISSUE TITLE
Automatic and internal Pip package management system

### ISSUE THREAD

**Issue by pedroguilhermelima** [python/devguide#469]
I'm trying to create a thing, an idea, a thought. This is about the Pip package management system used to install and manage software packages written in the Python programming language.

So I wanted it to be automatic. Instead of always typing ...

For example

~~~~
pip install example.py
~~~~

Solution
What if Python itself had this automatic feature internally?

For example

~~~~
impot example1 # runs pip install example.py
~~~~

Case

A. If you do not have the module, the module will be inserted.
B. If you have the module, check the installed version.

Summary
It would be a 'package.json, similar to the Nodejs' within Python.

Note
- I expect an answer
- Thank you for your attention and respect,
- I'm starting with Python and I have this idea
- If the community helps and if I can help, it would be an honor for this idea, implementation ^^

Regards,
Pedro Guilherme

**Comment by pedroguilhermelima** [comment]
Resume

What improvement?

Automatic and internal package. Forget 'pip-name-module' use only 'import'. With this, 'import is also the pip install name module'.

Case
A. If you have not, so add
B. If you have, check version

Regards,
Pedro Guilherme

**Comment by pedroguilhermelima** [comment]
See here https://github.com/python/peps/issues/922

**Comment by Mariatta** [comment]
Thanks for your interest in improving Python. However the devguide is not the right place to discuss the proposed idea. From the sound of it, perhaps [distutils-sig](https://mail.python.org/mailman3/lists/distutils-sig.python.org/)?

**Comment by pedroguilhermelima** [comment]
> Thanks for your interest in improving Python. However the devguide is not the right place to discuss the proposed idea. From the sound of it, perhaps [distutils-sig](https://mail.python.org/mailman3/lists/distutils-sig.python.org/)?

Thanks
