### ISSUE TITLE
Developers logs 404

### ISSUE THREAD

**Issue by JulienPalard** [python/devguide#483]
Home page has a link to https://devguide.python.org/developers.html redirecting to https://devguide.python.org/developers/ which gives a 404.

**Comment by Carreau** [comment]
Most link are 404 now for me, anything in "Full Table of Contents", like `/setup/`, `/help/` ... probably an error during the build on RTD.

**Comment by JulienPalard** [comment]
@Mariatta @willingc do you think it's related to the .readthedocs.yml thing?

**Comment by Mariatta** [comment]
That was my suspicion,.so I reverted the change (#484 ). It didn't seem to fix the issue.
Any other ideas?

**Comment by willingc** [comment]
I wiped the build container in the RTD UI and set the advanced settings for Sphinx build:

<img width="646" alt="Screenshot 2019-05-12 09 00 46" src="https://user-images.githubusercontent.com/2680980/57584818-937dfc80-7494-11e9-8d77-4d5986fe1a96.png">

[Ref in Sphinx docs](https://www.sphinx-doc.org/en/master/usage/builders/index.html#sphinx.builders.html.DirectoryHTMLBuilder)

I'll submit a revised PR for the RTD config file with updated builder information.

**Comment by Carreau** [comment]
Many thanks!
