### ISSUE TITLE
Broken link in Sphinx search on RTD

### ISSUE THREAD

**Issue by cdeil** [python/devguide#508]
At https://devguide.python.org/search/?q=sphinx there's currently a broken link http://devguide.python.org/index?highlight=sphinx to the "Python Developer’s Guide".

When I build the devdocs locally and do the same search for "sphinx", the link goes to `file:///Users/deil/work/code/devguide/_build/html/index.html?highlight=sphinx` (not the "index.html" instead of "index" at the end of the URL) and works.

So it seems there's a an issue on RTD, where either the Sphinx search index is outdated, or there's a bug in it's generation on that machine.

I see at https://readthedocs.org/projects/cpython-devguide/builds/9342659/ that the last build there passed 4 days ago.

Can anyone figure out what's wrong here?

**Comment by ncoghlan** [comment]
https://devguide.python.org/?highlight=sphinx works, so I wonder if that could be a bug when building in HtmlDir mode.

**Comment by hugovk** [comment]
I cannot reproduce this now, https://devguide.python.org/search/?q=sphinx has no link to "Python Developer’s Guide", and the other links all work:

![image](https://user-images.githubusercontent.com/1324225/94350584-30c0dd00-0058-11eb-9cb8-7cd0a4056824.png)

**Comment by cdeil** [comment]
Looks like it has been fixed somehow in the meantime.
