### ISSUE TITLE
Does not support number begin with 0?

### ISSUE THREAD

**Issue by ltoddy** [python/devguide#512]
![image](https://user-images.githubusercontent.com/20920763/61757434-2b805680-adf3-11e9-811e-d7ffb180ec5a.png)

**Comment by terryjreedy** [comment]
Your comment is off-topic here.  This is the repository for the guide to how to help develop the CPython implementation of python.  It is not for questions about how to use Python.  For the latter, try, for instance, the python-list mail list. 

To answer your question: 'no'.  Read the tutorial and the first few chapters of the language and library manuals, and in particular
https://docs.python.org/3/reference/lexical_analysis.html#integer-literals
