### ISSUE TITLE
Make https://devguide.python.org/committing/ simpler

### ISSUE THREAD

**Issue by brettcannon** [python/devguide#520]
Probably need more of a step-by-step todo list rather than all of that text so that a core dev who hasn't contributed in a while can more easily get their footing and merge a PR.

**Comment by aditisingh2362** [comment]
So do we need to remove all the text with todo list or just add a todo list?

**Comment by brettcannon** [comment]
@aditisingh2362 🤷‍♂ depends on which one leads to the better result for people.

**Comment by jablonskidev** [comment]
I'd like to work on the text for this page so that it'll be quicker for core devs to review the steps involved in accepting PRs from contributors. I should have something within the next couple days.
