### ISSUE TITLE
Simplify language in translation page

### ISSUE THREAD

**Issue by Mariatta** [python/devguide#522]
In https://devguide.python.org/documenting.html#i-have-a-translation-but-not-on-git-what-should-i-do it says:

"Just ask for help on the doc-sig mailing list and our python-fu, git-fu and bash-fu combined will help you create an appropriate repository. If you use a tool like transifex don’t worry. Keeping them in sync is not that hard."

That answer sounds a little demeaning to me.

- I would suggest not using terms like git-fu
- intsead of _"just ask for help on ..."_, use phrase like _"Ask for help on ..."_ or _"you can ask for help on ...."_
- Instead of _"if you use tool like transifex don't worry ... "_, we can say _"Using a tool like ... can help keeping them in sync"_

**Comment by SubhrajyotiSen** [comment]
Can I take this up?
