### ISSUE TITLE
How to return data from an infinite loop without breaking it?

### ISSUE THREAD

**Issue by evso9816** [python/devguide#537]
Purpose: I want to read the content of an infinite loop [class A], collect data, and send it off to another class B/function for further processing.
Problem: content in class A can be displayed. However, calling A's content into class B/function display empty list.
There are 2 files: test3.py and test4.py. The call and execution are done from test4.py

It should work, but it does not: Looking for advice, what is wrong? - Thanks.

Test4.py:
import test3
import time
objectTest = test3.test1()
def interface():
   A = objectTest.collectData() #call collectData from tset3
   B = (objectTest.name)        #call Instance attribute from test3
   print(B)                     #for testing purpose
   print(A)                     #for testing purpose
while True:
    interface()
    time.sleep(1)

Test3.py:
import random
import time

class test1:
    def __init__(self):
        self.name=[]

    def collectData(self):
        temp=[]
        #temp = list(self.name)  #for testing purpose
        temp = self.name.copy()
        print(temp)             #for testing purpose
        return temp

    def engine(self):
        while True:
            self.name.append(random.randrange(1,20))
            self.collectData()
            self.name.clear()
            time.sleep(2)

if __name__ == '__main__':
    object1 = test1()
    object1.engine()

**Comment by terryjreedy** [comment]
This is the issue tracker for improving the guide for developing CPython.  Users should ask questions elsewhere, such as python-list or stackoverflow.

**Comment by evso9816** [comment]
So sorry. I didn't know that it's not the right place to ask question. My bad!
