### ISSUE TITLE
Use imperative for commit title; fix example

### ISSUE THREAD

**Issue by terryjreedy** [python/devguide#577]
(See GvR's messages 363691 and 363740 on 2020 March 9 for https://bugs.python.org/issue39852.)
https://devguide.python.org/pullrequest/#making-good-commits has this descriptive example:
`bpo-42: the spam module is now more spammy (GH-NNNN)`
Guido strongly prefers the prevailing imperative style and would have that read
 `bpo-42: make the spam module more spammy (GH-NNNN)`

Possibly split the following paragraph into two and after "... what the purpose of the commit is." add something like
"The imperative form is strongly preferred to a descriptive form such as 'the spam module is now more spammy'.  Use `git log --oneline` to see existing title lines."

**Comment by gvanrossum** [comment]
While we're at it, let's also codify that the commit "title" shouldn't end in a period.

Also, let's more directly reference this guide to writing commit messages: https://chris.beams.io/posts/git-commit/

**Comment by DahlitzFlorian** [comment]
I would like to work on this if nobody is currently doing it.
