### ISSUE TITLE
CSS: code-blocks are not displayed in monospace

### ISSUE THREAD

**Issue by westurner** [python/devguide#581]
The code blocks in the Python Devguide are not in monospace? It's borking the ASCII art, and possibly other code blocks?

Example::
- RTD w/ Devguide Sphinx theme:
 
 https://devguide.python.org/garbage_collector/#memory-layout-and-object-structure
- GH rst2html:
 
 https://github.com/python/devguide/blob/master/garbage_collector.rst#memory-layout-and-object-structure

- GH raw:
 
 https://raw.githubusercontent.com/python/devguide/master/garbage_collector.rst

**Comment by westurner** [comment]
RTD theme:
- Chrome Android: not monospace
- FF Android: monospace

GH rst2html:
- *: monospace

**Comment by hugovk** [comment]
Can reproduce:

* Chrome macOS: monospace
* Chrome Android: not monospace

![image](https://user-images.githubusercontent.com/1324225/94406999-8215bd00-017b-11eb-91a9-d7b0e0b66a6e.png)


It gets the font from `pydoctheme.css` and looks like it's falling back to `sans-serif`:

```css
tt, code, pre {
    font-family: monospace, sans-serif;
    font-size: 96.5%;
}
```

However, `monospace` works on this test page:

![image](https://user-images.githubusercontent.com/1324225/94407444-1c760080-017c-11eb-8d58-74fc5285c356.png)

https://www.zipcon.net/~swhite/docs/computers/browsers/fonttest.html

Could it be the non-whole number `font-size: 96.5%;`?

**Comment by hugovk** [comment]
And this also happens at https://pip.pypa.io, so this is likely a https://github.com/python/python-docs-theme bug.

**Comment by alexprengere** [comment]
For the record, all the code-blocks from the devguide appears in monospace on my Chrome Android, as of August 2021. Should this be closed?

**Comment by westurner** [comment]
Looks good
