### ISSUE TITLE
Clarify step-by-step process to merge 'github' changes into 'master'

### ISSUE THREAD

**Issue by willingc** [python/devguide#59]
@brettcannon I wanted to clarify the CPython devguide process before making any merging branches and pushing update to master.

Assuming you want a no-ff merge instead of cherrypicking and/or rebasing.
### Process to merge 'github' branch into 'master'

```
# fetch any upstream changes and rebase onto local 
(master)$ git fetch upstream
(master)$ git rebase upstream/master

(master)$ git checkout github
(github)$ git rebase upstream/github

# check the diff between github and master
(github)$ git diff github..master

(github)$ git checkout master

# perform a no-fast forward merge and resolve conflicts (if needed)
(master)$ git merge --no-ff github

(master)$ git push upstream master
```

**Comment by berkerpeksag** [comment]
I think core devs can do it the way they prefer. I prefer ff merges, but the question is that do we really need to spend a lot of time to keep them in-sync? It's a temporary branch, `master` is not getting 10+ commits every day (`index.rst`, `developers.rst` and `experts.rst` are the most active files and they don't have a lot of Mercurial-specific contents), and the chance of getting a merge conflict is low (even if it does it's easy to fix it)

**Comment by willingc** [comment]
Thanks @berkerpeksag :sunny:

Keeping the branches in sync or at the very least the 'github' branch' always ahead, not behind, 'master' is important. It's a courtesy to community contributors who may not yet have the 'git' proficiency to go to master and grab the changes in master that are not in the github branch.

**Comment by berkerpeksag** [comment]
Working on the github branch requires to have:

1. Knowledge about the current development process of CPython
2. Experience with both Mercurial and Git

I don't think it's a suitable area to work on for someone who may not have experience with one of the VCSs yet.

**Comment by brettcannon** [comment]
Why do you want to merge `github` into `master` except when we are done with the `github` branch? Wouldn't it be easier to merge `master` into `github` (which is what I have been doing on occasion)? Most of the changes in `master` are spelling mistakes and such while all the churn is in `github`, so I would think we would want to merge from calm to crazy and not the other way around.

**Comment by willingc** [comment]
@brettcannon What I would like to see for contributors, perhaps I'm not doing a good job of explaining it, is:

- a branch that reflects the current production state (production)
- a branch that is alway ahead and never behind the production branch (staging)

Currently, some folks commit directly to master (which I view as production). Due to the direct commits to master, the staging branch (github) is frequently behind the production branch.

### Onboarding

This is problematic for onboarding new contributors. These contributors are going to read the instructions that they should submit a PR against the staging branch (github). As a contributor, I would expect that the staging branch include the production state plus any recently accepted changes/additions.

As a new contributor, the dev guide will frequently be the first thing that the contributor will read and work on. If they choose to contribute to the dev guide, it would be helpful to have a straightforward and pleasant contribution experience for them as it increases the likelihood of future contributions.

### Workflow

Wouldn't it simplify the workflow if everyone (those with or without push privileges) commits changes (large or small) to the `github` branch?

If that is not acceptable, I would love it if you could walk me through the desired steps to merge `master` into the `github` branch so I don't mess up the history. I'll commit to keeping the github branch from falling too far behind master.

**Comment by ncoghlan** [comment]
We're not as worried about linear history for the devguide as we are for CPython, so merges from `master`->`github` would look like:

    git checkout github
    git pull
    git merge origin/master
    git push

Thanks for being prepared to tackle that! I personally find collaborating on feature branches is always a bit of a pain (regardless of context), and that need to merge in changes made through the regular process is the main reason why :)

**Comment by brettcannon** [comment]
Nick's steps are what I have been doing, so that's fine by me.

As for people committing only to the `github` branch, that's fine by me as well (to help make everyone happy I will change the default branch that GitHub shows people to be the `github` branch instead of `master` and update Read the Docs to continue to display `master` by default). It's just you can't merge the `github` branch into `master` until we're ready to switch to git and thus delete the `github` branch entirely as this bifurcation is finished with. This is also why I don't view the `github` branch as a staging branch in the traditional sense since it's a band-aid solution for a transition that's only going to happen once.

**Comment by willingc** [comment]
@brettcannon @ncoghlan @berkerpeksag Thanks for the help on this. I'm going to close this as @zware has brought things up to date in `github` branch with #65. :heart:
