### ISSUE TITLE
Upgrade a new assessment options for each available content. 

### ISSUE THREAD

**Issue by elfalehed** [python/devguide#597]
I do believe that each content on the site, should be evaluated by the viewers, and pythoneers. That's why I think there should be an evaluation, rating system for each available article, Help, Pull request.

**Comment by terryjreedy** [comment]
People can and should evaluate things as they read.  If they find specific faults with our docs, they can and sometimes do open issues to fix them.  Unfortunately, we are not able to attend to them as expeditiously as we would like.  

Official rating system are something else, and tend to be either useless or abused. PyPI (now pypi.org) once had a package rating system and got rid of it.  Nor does it routinely display download statistics.
https://packaging.python.org/guides/analyzing-pypi-package-downloads/.
