### ISSUE TITLE
Update devguide style to use a similar theme as Docs

### ISSUE THREAD

**Issue by brettcannon** [python/devguide#6]
Originally from http://bugs.python.org/issue23951 .

**Comment by willingc** [comment]
I believe that this had been closed in the original issue but not marked as so before the issue was migrated here.

**Comment by berkerpeksag** [comment]
No, it should stay open: http://bugs.python.org/issue23951#msg270884

**Comment by zware** [comment]
I'd vote in favor of keeping rstlint.py (it's not ideal to have copies of it in multiple repositories, but it is pretty stable) and the mis-committed patch file was already reverted, but @berkerpeksag's first and third points in msg270884 stand.  I believe @lisroach wrote the patch that was committed, would you mind taking a look at those points?

**Comment by berkerpeksag** [comment]
Also, if you don't have time, I can have a look at this next week :)

**Comment by lisroach** [comment]
I'll take a look today! I think serving the images and javascript from the same page is a good idea, I'll see if I can implement it. I'll also try to make that hover color better. 

I am also of the opinion that rstlint should stay. Running 'make check' now shows some issues do come up, so maybe having it in place will encourage people to check their files before pushing.

**Comment by lisroach** [comment]
Okay, check out my commit here: https://github.com/lisroach/devguide/commit/7dc1131732fbfca757577fe5e6715f2c741420c0

I've hotlinked the py.png and copybutton.js from docs.python.com and deleted them from tools/static. Hotlinking normally isn't a great practice, but they are both python.org sites and I'm not sure of another way around it (I looked into intersphinx mappings but that is just for the documentation files). 

I ran into trouble with the sidebar.js. It is never referenced in layout.html, instead it is hardcoded in sphinx's classic/layout.html as `_static/sidebar.js`. Perhaps a bug should be opened with Sphinx. 

I also changed the hover link color for the headers, let me know if there is a color that would be easier to read :)

**Comment by lisroach** [comment]
Anyone get the chance to take a look at this yet? Thanks!

**Comment by brettcannon** [comment]
I just looked quickly and it seems fine. Can you send a PR to make it easier to review?

**Comment by lisroach** [comment]
Thanks Brett! It's pull request [#65](https://github.com/python/devguide/pull/65)

**Comment by zware** [comment]
Fixed by #65.
