### ISSUE TITLE
Diagnostic not loaded: Could not open 'Fields0.h5'

### ISSUE THREAD

**Issue by Sanjeev273** [python/devguide#611]
I have data file from smilei simulation: 'Fields0.h5' I got the msg in output file: Diagnostic not loaded: Could not open 'Fields0.h5'. Can anyone help me. is there anything wrong in python script or is it could be a problem in data file. I am not getting any error msg.I am using the following python script to acess the data:

import happi
S = happi.Open("/mnt/iusers01/fatpou01/phy01/v55735sk/scratch/SIM")
ne = S.Field(0, field = "-Rho_electron", label= "ne")
np = S.Field( 0, field= "Rho_proton", label = "np")
happi.multiPlot(ne, np, saveAs= " ./dens.png" )

**Comment by terryjreedy** [comment]
This issue tracker is for improving the devguide.  Ask question on python-list or Stackoverflow or ...
