### ISSUE TITLE
Quick Reference intro contains the same link twice.

### ISSUE THREAD

**Issue by waadnakhleh** [python/devguide#613]
Devguide quick reference intro says:

> Here are the basic steps needed to get [set up](https://devguide.python.org/setup/#setup) and contribute a patch. This is meant as a checklist, once you know the basics. For complete instructions please see the [setup guide](https://devguide.python.org/setup/#setup).

set up and setup guide contain a link to the same page, which is the following: https://devguide.python.org/setup/#setup

**Comment by manakwadhwa2002** [comment]
I can fix this issue please assign me with it. I have a good hand in front end development as well as in backend development. You can check my github profile at [Manak Wadhwa](https://github.com/manakwadhwa2002) [My Recent Work](https://www.mentord.co)

**Comment by Mariatta** [comment]
If folks want to fix it, please go ahead and propose a PR. We typically don't "assign" issues to people.
