### ISSUE TITLE
Broken intersphinx link to end-of-life branches

### ISSUE THREAD

**Issue by Julian** [python/devguide#618]
The [Sphinx inventory for the devguide](https://devguide.python.org/objects.inv) shows that the [end of life branches section](https://devguide.python.org/devcycle/#end-of-life-branches) should live at:

```
⊙  ~[sphinx:python] -m sphinx.ext.intersphinx 'https://devguide.python.org/objects.inv' | rg eol                                                                                                julian@Air ●
        eolbranch                                End-of-life branches                    : devcycle/#eolbranch
```

i.e. https://devguide.python.org/devcycle/#eolbranch, but that's a broken fragment link (which my linkcheck doc builder notified me of). The correct path + fragment seems to be `devcycle/#end-of-life-branches` in the version currently published

This breaks intersphinx'ing to that section. I don't see how this could be unless the objects.inv being served by https://devguide.python.org/objects.inv is somehow not from later builds, but maybe it's too early in the day to be thinking too hard about Sphinx error conditions for me.

**Comment by ezio-melotti** [comment]
The link seems to work, so I'm closing this.

**Comment by Julian** [comment]
Yep seems it's been fixed since.
