### ISSUE TITLE
Add proper readme to repo for first time contributors.

### ISSUE THREAD

**Issue by Aayush-hub** [python/devguide#657]
**Describe the enhancement or feature you'd like**

As I landed to this repo to contribute to this project , I can't understand the work tree of the repo and from where to start changing files. I felt something missing which is the detailed readme to the project for first time contributors who wants to contribute their part to the organisation. I saw a redirecting link which landed me to a site which was full of knowledge but was not understandable. So, it will be great for first time contributors if this repo gets a simple quick start guide and details of file-work tree ***in its readme itself***  .

**Comment by Bonifacio2** [comment]
This sounds like a #624 duplicate.

**Comment by pradyunsg** [comment]
Duplicate of #624
