### ISSUE TITLE
Consider removing out of date instructions for obsolete Python versions that are no longer developed or supported

### ISSUE THREAD

**Issue by CAM-Gerlach** [python/devguide#661]
**Describe the enhancement or feature you'd like**
There are a number of places in the dev guide that still discuss how to do various development tasks (modify code, submit PRs, etc) for versions of Python <3.6 that are EoL and no longer developed or supported. As in most cases these (particularly Python 2.7) simply add extra complexity, contingencies and cruft without providing any real practical benefit to current or future Python contributors, now that development of those obsolete versions has ceased, it would considerably simplify the guide for users to eliminate these vestigial sections where appropriate, in cases where there is no plausible value (historical or otherwise) in retaining them for posterity.

**Describe alternatives you've considered**
The alternative would be keeping them around forever, which would be unsustainable in the long run as the number of EoLed versions grow over time. As all these versions have been frozen for at least ≈6 months (and the most significant one, 2.7, for a year or more), delaying longer for some indefinite period of time doesn't appear prudent either.

**Additional context**
I've developed and tested the following regex to identify potential candidates for removal: `([Pp]y(thon)? ?(1\.?[0-9]|2\.?[0-7]|3\.?[0-5]))|2\.?7|3\.[0-5]`. Of course, every instance would be carefully reviewed, and conservatively retained if there is any doubt as to its continuing value. I'm happy to take this on promptly once I get a go-ahead.

**Comment by hugovk** [comment]
Please see PR https://github.com/python/devguide/pull/1227.
