### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by euberdeveloper** [python/devguide#667]
I don't know if this is the right repo for this issue.

Please, for the sake of my eyes, make a dark theme for the python docs site!!!

**Comment by euberdeveloper** [comment]
Altimenti andate al lago

**Comment by Mariatta** [comment]
There is an open PR for it in the python-docs-theme repo https://github.com/python/python-docs-theme/pull/44
We need folks to help review and test it.

**Comment by hugovk** [comment]
Here's the test site for the PR:

https://septatrix.github.io/cpython-dark-docs/

**Comment by septatrix** [comment]
I actually just made a few final changes and performed a bit of cleanup. Also the demo side got updated to python 3.10. I would be very pleased if someone were to review the changes as the PR has been open for a long time and this is IMO a long overdue feature.

**Comment by FalleN321** [comment]
> I don't know if this is the right repo for this issue.
> 
> Please, for the sake of my eyes, make a dark theme for the python docs site!!!

Hello ,

I have 2 solutions for you. You don't have to wait for anyone to make dark theme for the python docs site.

here are two proposed solutions:

1- Use opera GX browser , It has a built-in Dark mode , which works for (almost) every single website. I'm using it right now and have have dark themed Python docs site.

2- Use Google Chrome and install an extension called (Dark Reader) it has option to convert a specific site to dark mode and adjust the contrast and brightness.

# NOTE: this is only applicable for PC. unfortunately I don't have any solution for the mobile devices.

**Comment by euberdeveloper** [comment]
Hi, I have already installed that extension and works great.

As a suggestion, I think that it could be useful an official dark version of the site, for this reason I have not still closed the issue

**Comment by pypdeveloper** [comment]
What would be the right repo to suggest changes to the documentation?

> I don't know if this is the right repo for this issue.
> 
> Please, for the sake of my eyes, make a dark theme for the python docs site!!!

**Comment by terryjreedy** [comment]
Doc content is handled on python/cpython.  Mariatta already answered for the web pages.
"There is an open PR for it in the python-docs-theme repo python/python-docs-theme#44"
