### ISSUE TITLE
Update compiler docs with the new parser changes

### ISSUE THREAD

**Issue by pablogsal** [python/devguide#678]
The documentation regarding the design of CPython's compiler should be updated to include the new changes in the parser:

* AST nodes are not generated anymore by hand (`ast.c` is almost gone) but generated directly by the parser.
* There is a new API for working with `asdl_seq` nodes.

**Comment by Fidget-Spinner** [comment]
Hi Pablo, I'd like to work on this. Admittedly I'm still inexperienced when it comes to the compiler. So this might take some time.

**Comment by pablogsal** [comment]
Thanks @Fidget-Spinner! The section that needs replacing is:

https://github.com/python/devguide/blob/master/compiler.rst#parse-tree-to-ast

Basically the Python/ast.c is not used anymore because the parser generates the AST (see PEP 617) and the APIs mentioned there are old, as we use typed information now:

https://bugs.python.org/issue41746
