### ISSUE TITLE
Rename master to main...

### ISSUE THREAD

**Issue by matrixise** [python/devguide#689]
Since May 3rd, CPython uses the main branch as the default branch. We should do the same with this repository and keep the same naming system like this one.

**Comment by Mariatta** [comment]
In the [Steering Council](https://mail.python.org/archives/list/python-dev@python.org/thread/XCUXKL5LMQHO7GDQUABS4KE6JSMRVUQN/#GDAUZKYB6GP3A3ZGBSQ4KQ7R6QFIZHZC) announcement, it says:

> The group is going to discuss the
>   timeline and how to approach this with **other repositories under the Python**
>   organization in some future meeting.

So I was waiting for their updates on it.

**Comment by matrixise** [comment]
Thanks, @Mariatta  I was not aware of the announcement...

**Comment by ewdurbin** [comment]
this is complete!
