### ISSUE TITLE
Duplicate text on 11.2. Becoming a member of the Python triage team

### ISSUE THREAD

**Issue by Bonifacio2** [python/devguide#702]
Part of the section is as follows:

> Any existing developers on b.p.o can transition into becoming a Python triager. They can request this to any core developer, and the core developer can pass the request to the Python organization admin on GitHub. The request can be made confidentially via a DM in Zulip or Discourse, or publicly by opening an issue in the core-workflow repository.
> 
> Any contributor who is not already a developer on b.p.o can also self-nominate to be a member of Python triage team. They can request this to any core developer, confidentially via DM in Zulip or Discourse, or publicly by opening an issue in core-workflow. If a core developer agrees and is willing to vouch for them, the core developer can pass the request to the GitHub administrator. They should also be added as developer on bpo.

Most of the text on the paragraphs is the same, so I guess there's a leaner way to write it.

Source: https://devguide.python.org/triaging/#becoming-a-member-of-the-python-triage-team

**Comment by slateny** [comment]
Looks like it was resolved per #814
