### ISSUE TITLE
The "copy to clipboard" icon seems broken in the new theme

### ISSUE THREAD

**Issue by Mariatta** [python/devguide#710]
**Describe the bug**
It seems like the "Copy to clipboard" icon is not showing up properly. Instead, there is a long text that says "Copy to clipboard"

**Expected behavior**
I think it should show the copy icon instead of the text.

**Screenshots**
![Screen Shot 2021-06-04 at 11 12 07 AM](https://user-images.githubusercontent.com/5844587/120845728-0ba93600-c526-11eb-8590-997f9dda3e43.png)

**Additional context**
The image path was pointing to https://devguide.python.org/#_static/copy-button.svg
Is that the correct path?

**Comment by pablogsal** [comment]
Is only broken in the front page. This is a bug in the extension, see:

https://github.com/executablebooks/sphinx-copybutton/issues/121

**Comment by pablogsal** [comment]
Fixed by https://github.com/python/devguide/pull/715

**Comment by Mariatta** [comment]
Cool! Thanks!
