### ISSUE TITLE
Error in table of contents on the gitbootcamp page

### ISSUE THREAD

**Issue by shreyanavigyan** [python/devguide#711]
In the git bootcamp cheatsheet, there's an error in the table of contents. Screenshot -

![image](https://user-images.githubusercontent.com/74560907/120925230-49a88480-c6f5-11eb-8b97-39b81257e5f1.png)

**Comment by akulakov** [comment]
I will make a PR to delete this list of contents since an exact copy already shows up on the right hand panel, as shown in the screenshot.

**Comment by shreyanavigyan** [comment]
@akulakov Thanks! https://github.com/python/devguide/pull/712 fixes this! Closing this.
