### ISSUE TITLE
Document ``build.bat`` counterparts for many instructions using ``make``

### ISSUE THREAD

**Issue by Fidget-Spinner** [python/devguide#716]
A few sections using ``make`` don't always have their Windows ``build.bat`` counterpart. One example here:
https://devguide.python.org/grammar/#checklist .

The docs should be updated to have the equivalent ``build.bat`` command beside ``make``.

**Comment by Fidget-Spinner** [comment]
To get the ball rolling, I'll work on the example I mentioned in the first message. If anyone finds anything in other sections, reporting them here or fixing them would be a great help :).

**Comment by encukou** [comment]
There's one in CPython at the end of `Tools/scripts/stable_abi.py`, and the corresponding commands at the end of https://devguide.python.org/c-api/ might also be simplified. If you know the proper incantations for Windows, please add them!
But these might need to be added to `build.bat` first. (And if you want to go deeper: I couldn't find instructions for adding things to `build.bat`.)

**Comment by Fidget-Spinner** [comment]
``./python ./Tools/scripts/stable_abi.py --generate-all ./Misc/stable_abi.txt`` doesn't work on MSVC (Windows) because it seems to require GCC/Clang. I will add a note in the docs somewhere for that.
