### ISSUE TITLE
Example for Running a single test case fails

### ISSUE THREAD

**Issue by SimiCode** [python/devguide#717]
**Describe the bug**
When I run `./python -m unittest -v test.test_abc.TestABC` as suggested in the dev-guide,
I get an error:
```
AttributeError: module 'test.test_abc' has no attribute 'TestABC'
```

**Expected behavior**
fix this by adding "_Py" and run it as
`./python -m unittest -v test.test_abc.TestABC_Py`

**Comment by terryjreedy** [comment]
I verified the problem and the fix.  Can you make a PR, if that is what we do for his repository?

**Comment by SimiCode** [comment]
PR added: https://github.com/python/devguide/pull/718
