### ISSUE TITLE
I have never seen such a dumb API design

### ISSUE THREAD

**Issue by GF-Huang** [python/devguide#723]
https://docs.python.org/3/library/itertools.html#itertools.groupby

> itertools.groupby(iterable, key=None)¶
Make an iterator that returns consecutive keys and groups from the iterable. The key is a function computing a key value for each element. If not specified or is None, key defaults to an identity function and returns the element unchanged. Generally, the iterable needs to already be sorted on the same key function.

I don't know who design this stupid API, You have to sort your data first before using `groupby` avoid the unexpected behavior. Why not tell me design and make a CPU by myself before use python? Take a look the `GroupBy` of C#, why you so stupid?

**Comment by nanjekyejoannah** [comment]
Can you please open the issue on bpo (https://bugs.python.org/). It looks like an issue regarding API design no? Note, calling volunteers stupid will not help in any way.

**Comment by zware** [comment]
This blatant violation of our code of conduct is in any case misplaced. If you want to pursue trying to get this API changed, try either a bug report or a message to one of the development mailing lists. Further CoC violations are likely to have you just banned, though; please be considerate of others.

**Comment by nanjekyejoannah** [comment]
Can someone with rights do the same, i.e close here : https://github.com/python/pythondotorg/issues/1812 ?
