### ISSUE TITLE
Issue with Custom Domain on ReadTheDocs

### ISSUE THREAD

**Issue by Mariatta** [python/devguide#747]
I received email from Readthedocs today regarding custom domain ownership validation for devguide.python.org

> We are reaching out to you because you have at least one custom domain on https://readthedocs.org using a deprecated or unsupported validation method.

> We use Cloudflare for SaaS to provide SSL certificates and CDN on all documentation we host. In the past there were ways to deploy your own CDN, but that is no longer needed and is unsupported. A CDN is now natively supported by our platform, and the cache is automatically cleared on each build.

> We are currently hoping to mitigate this issue by working around it, but we strongly recommend that you change your DNS configuration to a supported method. This will ensure that future changes don't impact documentation hosting or the SSL certs associated with your custom domain.

> Please follow the steps described at https://docs.readthedocs.io/en/stable/custom_domains.html?#custom-domain-support to add a CNAME record in your DNS that points the domain to readthedocs.io. If you are using a custom method like proxying to us and can't migrate to using a CNAME record, please contact us via support at https://readthedocs.org/support/.

I'm not familiar DNS configuration, I don't think I have the access to do it.

Would someone from @python/infrastructure-staff  be able to help with this?

Thanks.

**Comment by ewdurbin** [comment]
Can the user `ewdurbin` (me) on ReadTheDocs.org be added as an admin on the project to make sure this is taken care of?

**Comment by Mariatta** [comment]
I have added you to the `cpython-devguide` project on Readthedocs.org Thanks.

**Comment by ewdurbin** [comment]
All sorted!

**Comment by Mariatta** [comment]
Thanks!
