### ISSUE TITLE
Add a paragraph to the parser guide that actions must not mutate ASTs

### ISSUE THREAD

**Issue by cfbolz** [python/devguide#765]
I think it would be good if the parser guide had add a paragraph that stresses that actions must not mutate existing AST nodes due to the memoization (I made that mistake in pypy today ;-)). If you think that's a good idea I am happy to making an attempt.

**Comment by pablogsal** [comment]
> I think it would be good if the parser guide had add a paragraph that stresses that actions must not mutate existing AST nodes due to the memoization (I made that mistake in pypy today ;-)). If you think that's a good idea I am happy to making an attempt.

Please, go ahead!
