### ISSUE TITLE
Is https://devguide.python.org/ still updated since master branch was renamed to main?

### ISSUE THREAD

**Issue by vstinner** [python/devguide#777]
https://devguide.python.org/ says "Last updated on Dec 02, 2021." The date Dec 2 is that date when the master branch was renamed to the main branch. But... it's also the latest commit: https://github.com/python/devguide/commits/main

I don't know if the build is triggered by a Git commit, or one a day.

I don't know if it's real issue. I prefer to open an issue to not forget. Feel free to close it if the automation works as expected ;-)

**Comment by vstinner** [comment]
cc @Mariatta @willingc @JulienPalard

**Comment by Mariatta** [comment]
I checked the reeadthedocs setting for devguide and it was already set to build from the main branch.

**Comment by vstinner** [comment]
Thank you for checking ;-)
