### ISSUE TITLE
More than 4 cameras error.

### ISSUE THREAD

**Issue by cespedesk** [python/devguide#781]
I am trying to make a software to run 6 cameras but it can only run 4 at the same time.
Is there a camera amount limit?
This is my code 

import threading
import multiprocessing
import cv2
import numpy as np
import time

# In screen FPS counter
timeStamp=time.time()
fpsFilt=0
font=cv2.FONT_HERSHEY_SIMPLEX

dispW=1280
dispH=720

dispW1=640
dispH1=480

# Camera inputs 
# v4l2-ctl --list-devices

cap=cv2.VideoCapture('/dev/video0')
cap.set(cv2.CAP_PROP_FRAME_WIDTH, dispW1)
cap.set(cv2.CAP_PROP_FRAME_HEIGHT, dispH1)

cap1=cv2.VideoCapture('/dev/video2')
cap1.set(cv2.CAP_PROP_FRAME_WIDTH, dispW1)
cap1.set(cv2.CAP_PROP_FRAME_HEIGHT, dispH1)

cap2=cv2.VideoCapture('/dev/video4')
cap2.set(cv2.CAP_PROP_FRAME_WIDTH, dispW1)
cap2.set(cv2.CAP_PROP_FRAME_HEIGHT, dispH1)

cap3=cv2.VideoCapture('/dev/video6')
cap3.set(cv2.CAP_PROP_FRAME_WIDTH, dispW1)
cap3.set(cv2.CAP_PROP_FRAME_HEIGHT, dispH1)

cap4=cv2.VideoCapture('/dev/video8')
cap4.set(cv2.CAP_PROP_FRAME_WIDTH, dispW1)
cap4.set(cv2.CAP_PROP_FRAME_HEIGHT, dispH1)

def pro1():
    global timeStamp
    global fpsFilt
    global font
    while True:
        success, img = cap.read()
        dt=time.time()-timeStamp
        timeStamp=time.time()
        fps=1/dt
        fpsFilt=.9*fpsFilt + .1*fps
        #print(str(round(fps,1))+' fps')
        
        cv2.putText(img,str(round(fpsFilt,1))+' fps',(0,30),font,1,(0,0,255),2)

        cv2.imshow('detCam1',img)
        if cv2.waitKey(1)==ord('q'):
            break
    cap.release()

def pro2():
    global timeStamp
    global fpsFilt
    global font
    global img
    while True:
        success, img = cap1.read()
        dt=time.time()-timeStamp
        timeStamp=time.time()
        fps=1/dt
        fpsFilt=.9*fpsFilt + .1*fps
        
        cv2.putText(img,str(round(fpsFilt,1))+' fps',(0,30),font,1,(0,0,255),2)

        cv2.imshow('detCam2',img)

        if cv2.waitKey(1)==ord('q'):
            break
    cap1.release()
    cv2.destroyAllWindows()
    
def pro3():
    global timeStamp
    global fpsFilt
    global font
    while True:
        success, img = cap2.read()

        dt=time.time()-timeStamp
        timeStamp=time.time()
        fps=1/dt
        fpsFilt=.9*fpsFilt + .1*fps
        #print(str(round(fps,1))+' fps')
        cv2.putText(img,str(round(fpsFilt,1))+' fps',(0,30),font,1,(0,0,255),2)

        cv2.imshow('detCam3',img)

        if cv2.waitKey(1)==ord('q'):
            break
    cap2.release()
    cv2.destroyAllWindows()

def pro4():
    global timeStamp
    global fpsFilt
    global font
    while True:
        success, img = cap3.read()

        dt=time.time()-timeStamp
        timeStamp=time.time()
        fps=1/dt
        fpsFilt=.9*fpsFilt + .1*fps
        #print(str(round(fps,1))+' fps')
        cv2.putText(img,str(round(fpsFilt,1))+' fps',(0,30),font,1,(0,0,255),2)

        cv2.imshow('detCam4',img)

        if cv2.waitKey(1)==ord('q'):
            break
    cap3.release()
    cv2.destroyAllWindows()

def pro5():
    global timeStamp
    global fpsFilt
    global font
    while True:
        success, img = cap4.read()

        dt=time.time()-timeStamp
        timeStamp=time.time()
        fps=1/dt
        fpsFilt=.9*fpsFilt + .1*fps
        print(img)
        cv2.putText(img,str(round(fpsFilt,1))+' fps',(0,30),font,1,(0,0,255),2)

        #cv2.imshow('detCam5',img)

        if cv2.waitKey(1)==ord('q'):
            break
    cap4.release()
    cv2.destroyAllWindows()

t1 = multiprocessing.Process(target=pro1)
t2 = multiprocessing.Process(target=pro2)
t3 = multiprocessing.Process(target=pro3)
t4 = multiprocessing.Process(target=pro4)
t5 = multiprocessing.Process(target=pro5)

t1.start()
time.sleep(1)
t2.start()
time.sleep(1)
t3.start()
time.sleep(1)
t4.start()
time.sleep(1)
t5.start()

the last processes prints none for img.
Is there a way to run 6 cameras?

**Comment by terryjreedy** [comment]
This is the repository and issue tracker for improving the guide for people who improve CPython, located at https://devguide.python.org/.   Questions about using Python should be directed elsewhere, such as stackoverflow.com or https://mail.python.org/mailman/listinfo/python-list.  If you do ask elsewhere, you should post properly indented code by copying and pasting what you actually run.  Also remove the duplication in the 'pro' functions by adding parameters for what is different. 

To answer you question, there should be no limitation in Python on number of cameras.  However, you computer or even OS might have such a limitation.
