### ISSUE TITLE
Is "current owners" section up-to-date?

### ISSUE THREAD

**Issue by sobolevn** [python/devguide#790]
I am reading through https://devguide.python.org/devcycle/#current-owners and it feels like it might a bit outdated.

For example:
- https://pyfound.blogspot.com/2021/12/a-message-from-psfs-outgoing-executive.html

Should it be changed? Are there any other changes?

**Comment by hugovk** [comment]
In https://github.com/python/devguide/pull/792, @ewdurbin updated it to remove Ewa.

@ewdurbin Are the others up to date? Thanks!

**Comment by ewdurbin** [comment]
Yes, list is current after that change.
