### ISSUE TITLE
Issue with https://devguide.python.org/compiler/

### ISSUE THREAD

**Issue by mark1234N** [python/devguide#810]
The AST to CFG step is handled mostly by two functions called by _PyAST_Compile(); _PySymtable_Build() and compiler_mod(). The former is in Python/symtable.c while the latter is in Python/compile.c.

should read:

    The AST to CFG step is handled mostly by THREE functions called by _PyAST_Compile(); _PySymtable_Build() and compiler_mod(). ...

**Comment by pochmann** [comment]
[As you were already told](https://stackoverflow.com/q/70944008/12671057), those *are* only two functions, not three.

**Comment by zware** [comment]
`_PySymtable_Build` and `compiler_mod` are two functions; `_PyAST_Compile` is a third that does not call itself.  I'm not an expert on the compiler stuff, but from an English interpretation there's no problem here.
