### ISSUE TITLE
Install Dependencies for macOS not sufficient to build gdbm

### ISSUE THREAD

**Issue by shimst3r** [python/devguide#817]
**Describe the bug**

Following the [setup instructions for macOS](https://devguide.python.org/setup/#macos-and-os-x) and installing all dependencies via Homebrew, building the optional module `_gdbm` does not work.

**Expected behavior**

Following the setup instructions, I expect a full CPython build.

Adding the missing steps to either the documentation or `.configure` would be highly appreciated. 😊

**Screenshots**

<img width="1061" alt="_gdbm bits not found" src="https://user-images.githubusercontent.com/11292060/155973237-242cff11-91e7-4f40-a76e-51d5d91488f4.png">

**Additional context**

I'm running macOS Monterey Version 12.2.1 (21D62) on a Mac mini M1.

**Comment by adamweiss** [comment]
I think I have a solution for this. I'll create a pull request in the next day or two

**Comment by methane** [comment]
I am using Monterey 12.6 on Intel Mac and I can build gdbm without any hack.
clang uses `/usr/local/include` by default.

Maybe, M1 Homebrew uses `/opt/homebrew` as prefix and clang don't use `/opt/homebrew/include` by default.
So adding `CFLAGS=-I/opt/homebrew/include` would be a simple solution.

I will replace my Intel Mac to M1 mac tomorrow. I will check it.

**Comment by adamweiss** [comment]
@methane This was on my M1 Mac. `CFLAGS=-I${HOMEBREW_PREFIX}/include` did work for the main branch, however on 3.9, the build finishes, however:

```
Failed to build these modules:
_decimal   
```
It builds successfully when explicitly specifying gdbm and xz.

**Comment by methane** [comment]
I confirmed that CFLAGS=-I/opt/homebrew/include LDFLAGS=-L/opt/homebrew/lib is enough to build Python 3.8 and 3.11.

**Comment by methane** [comment]
I don't know what is Homebrew recommendation. C_INCLUDE_PATH/LIBRARY_PATH or CFLAGS/LDFLAGS.
