### ISSUE TITLE
Update label names in the triaging section

### ISSUE THREAD

**Issue by ezio-melotti** [python/devguide#821]
The labels used in the `python/cpython` repo have been updated In python/core-workflow#432 and python/bedevere#419.

https://devguide.python.org/triaging/ should be updated accordingly.

https://discuss.python.org/t/github-issues-migration-label-mapping/14212 has more information about the labels.

**Comment by pgadige** [comment]
@Mariatta I'm working on this one. May I share a draft PR?

**Comment by Mariatta** [comment]
Sure @pgadige go for it.

**Comment by ezio-melotti** [comment]
@pgadige, are you still working on this?

**Comment by pgadige** [comment]
@ezio-melotti Yes, I'm working on it. I was MIA for a few days due to a personal urgency.

**Comment by ezio-melotti** [comment]
Now that the migration is done, labels are documented in three places:
* https://devguide.python.org/gh-labels/
* https://devguide.python.org/triaging/
* https://github.com/python/cpython/labels

We are also still updating labels and their names as we adapt to the new workflow, which means that whenever we add/remove/update a label, we also have to update the devguide.

It might be easier to just link to the labels page on `python/cpython`, however not all labels there have descriptions.  This is intentional since some of them are self-explanatory and adding descriptions clutters the "labels" dropdown.

Maybe the best approach would be to document groups of labels and labels that trigger bots or have special meanings and then link to https://github.com/python/cpython/labels for the full list.

**Comment by za** [comment]
Hi @pgadige allow me to initiate the PR. @ezio-melotti I've drafted a PR. Am I in the right direction? I haven't filled the description though.

**Comment by za** [comment]
I've added the description.

**Comment by za** [comment]
I've added the description.

**Comment by AA-Turner** [comment]
Labels are now consolidated into one place in the devguide (https://devguide.python.org/triage/labels/), but I just cut-and-pasted, so there is rampant duplication and likely a lot of the content is outdated (but no less outdated than previously).

A
