### ISSUE TITLE
Update translators table

### ISSUE THREAD

**Issue by ezio-melotti** [python/devguide#835]
The [translators table](https://devguide.python.org/documenting/#translating) still includes bpo usernames.  It should be updated to use GitHub usernames.  In addition, the expert index contains another [table that lists translators](https://devguide.python.org/experts/#documentation-translations) that perhaps could be removed.

**Comment by hugovk** [comment]
Tip for implementing:

* Click each person's name to see their bpo profile

* It should show their "GitHub Name"

* Then replace the bpo link in the table with `https://github.com/username`

> In addition, the expert index contains another [table that lists translators](https://devguide.python.org/experts/#documentation-translations) that perhaps could be removed.

It would be good to replace this with a link to the first table.

**Comment by sumukhmg** [comment]
hello @hugovk and @ezio-melotti can you please assign this issue to me, I'm a beginner in open source.Thank you! hoping to contribute more to opensource

**Comment by sumukhmg** [comment]
Thank you!

**Comment by sumukhmg** [comment]
made a pr #837  for the same 
Thank you!

**Comment by ezio-melotti** [comment]
Thanks for the PRs @sumukhmg!

I merged #836 and #838, and closed #837.  Generally there should be a single PR per issue.  You can make additional changes by adding commits to the branch -- when you push them to your fork GitHub will automatically updated the PR.

**Comment by sumukhmg** [comment]
hello @ezio-melotti! I have made only one pr #837 others are not mine.

**Comment by hugovk** [comment]
> Hi @sumukhmg! Just go ahead and create a PR, thank you!
> 
> I see you already made [osama24sy#1](https://github.com/osama24sy/devguide/pull/1) in your own fork, make sure to create a PR in this repo too :)

Ah sorry, I mixed up usernames here. Hopefully you can find something else to contribute, thanks anyway for your effort!

**Comment by sumukhmg** [comment]
It's ok, hoping to contribute to other issues🙂
