### ISSUE TITLE
Move the "Translations" section into its own page.

### ISSUE THREAD

**Issue by Mariatta** [python/devguide#842]
I think documentation translation effort is big and important enough to have its own page, and its own heading in the sidebar menu.

Currently it is a sub-section under "Documenting" page, and we have to scroll all the way down to find it.

https://devguide.python.org/documenting/#translating

cc @JulienPalard

**Comment by encukou** [comment]
Please keep the `#translating` link working though (i.e. a stub section with a link to the new place).

**Comment by ezio-melotti** [comment]
Done in #901.
