### ISSUE TITLE
Question: What version of sphinx should be used to build python docs?

### ISSUE THREAD

**Issue by Mariatta** [python/devguide#85]
Dev guide only mentioned that we are expected to install a *recent* version of sphinx.
http://cpython-devguide.readthedocs.io/en/latest/documenting.html#building-doc

By *recent*, do you mean *latest*?
Or, is there a minimum version that is acceptable?

Thanks :)

**Comment by willingc** [comment]
Hi @Mariatta. The minimum acceptable version should be found in Sphinx's`conf.py` file https://github.com/python/cpython/blob/master/Doc/conf.py#L37 It states 1.2 is acceptable. Sphinx is currently at 1.5. 

@bitdancer Do you have a recommendation? Thanks!

**Comment by Mariatta** [comment]
Thanks @willingc  :) I've been using 1.3.5, so I guess I'm fine for now.
Any idea if there's difference in the output when using these different sphinx versions?
(I'm new-ish to sphinx)

Can add into devguide that the minimum sphinx version is 1.2?
As newcomer I didn't know that I could look into conf.py to find out which sphinx version is needed.

**Comment by brettcannon** [comment]
You should be able to just use the latest version. As for the output, it should be the same. The only real change I ever notice is that newer versions warn about different things.

**Comment by willingc** [comment]
I would recommend the latest stable version of sphinx in the devguide as @brettcannon mentions. Thanks @Mariatta. Feel free to ping me directly if you have specific sphinx questions too.

**Comment by Mariatta** [comment]
Thanks @brettcannon and @willingc :) 
I proposed a PR to the devguide based your input.
