### ISSUE TITLE
Document Discourse

### ISSUE THREAD

**Issue by ezio-melotti** [python/devguide#853]
Now that Discourse has become more integral to our workflow, it would be helpful to add a section about it to the devguide.

The section should include:
- What's the purpose of Discourse, where to find it, and how to join it
- An overview of the categories and trust levels
- Recommended basic configuration and tips, such as:
  - going through the two `@discobot` tutorials (can be activated by replying to the welcome message)
  - how to follow certain categories, and getting notified for either new topics or all messages
  - how to follow individual threads
  - how to enable the "Mailing list mode" (though I haven't tried it yet, so I'm not sure how it works)

Doing this will have at least two advantages:
* we will ensure that people can follow the discussions more effectively
* we will have something to point to new (and old) contributors

https://discuss.python.org/t/python-discourse-quick-start/116 has some more tips.

This is also somewhat related to https://discuss.python.org/t/triaging-reviewing-fixing-issues-and-prs/15365 -- even though it's not about issues/PRs, it helps keeping devs in the loop and using their time more effectively.

**Comment by ezio-melotti** [comment]
Somehow I managed to miss that -- I thought I searched in the devguide too, but I must have only searched in the [devguide issues](https://github.com/python/devguide/issues?q=is%3Aissue+discourse) and found nothing relevant.  Thanks for pointing it out!

That intro covers most of the first two points of my initial message.  The rest should still be documented, perhaps in a sub-section.

**Comment by georgically** [comment]
I can pick this up and expand on the contents. I'll try to submit a PR by 27 May 2022. Will update if I encounter any issues since I'm still pretty new.

**Comment by ezio-melotti** [comment]
Thanks for picking this up!
I think you can expand the section linked by @ncoghlan, which already covers some of the things I mentioned in the first post.  You can add additional paragraphs or a sub-section that covers the rest.

**Comment by georgically** [comment]
Hi some updates. Still working on the edits. slight delay in delivery due to some private family matters. Will try to submit by the end of the month.
