### ISSUE TITLE
Document GitHub CLI

### ISSUE THREAD

**Issue by ezio-melotti** [python/devguide#861]
https://cli.github.com/ should be documented in https://devguide.python.org/gitbootcamp/, on its own FAQ and/or integrated with the other FAQs.

Useful commands (shared on Discord):
* `gh auth login` (once)
* `gh pr create`: to create a PR
* `gh pr checkout`: to checkout others' PRs
* `gh config set git_protocol ssh` (once): to be able to push to others' PRs
* `gh config set browser "/Applications/Firefox.app/Contents/MacOS/firefox"`: to set the browser

**Comment by erlend-aasland** [comment]
Note, there is already a short mention of GitHub CLI: https://devguide.python.org/gitbootcamp/#downloading-other-s-patches
