### ISSUE TITLE
Typo in the translation section

### ISSUE THREAD

**Issue by sanketgarade** [python/devguide#872]
**Describe the bug**

At the below link, I think the file `bugs.po` is mistakenly written as `bugs.py`.
https://devguide.python.org/documenting/#starting-a-new-translation

> When `tutorial/`, `bugs.py` and `library/functions` are complete, ask on the translation mailing list for your language to be added in the language picker on docs.python.org.

**Expected behavior**

If it indeed is a typo, then it can be corrected.
Similarly it will be better to write `library/functions.po` instead of `library/functions` just to make it clearer.

I already have a PR #871 for another change in the same section. If you want I can fix this in the same PR or make a separate one for it.

**Comment by Mariatta** [comment]
Thank you for the report. I'm not too familiar with the translation efforts. Perhaps @JulienPalard can clarify here.

However, it's better to fix this separately instead of bundling the change with your other PR.
