### ISSUE TITLE
Provide the status of Python branches and versions as a csv

### ISSUE THREAD

**Issue by Mariatta** [python/devguide#883]
**Describe the enhancement or feature you'd like**
Currently we have to open a browser and read the status of Python branches.

https://devguide.python.org/#status-of-python-branches

It would be great if that info is available in CSV format instead of in an rst table.

If the data is in CSV, we can then write scripts to programmatically parse the table and find the info we need.

According to @ezio-melotti , Sphinx support the `.. csv-table::` directive, so we can use that instead of the current rst table syntax.

**Comment by warsaw** [comment]
There's also [endoflife.date](https://endoflife.date/python) for Python, which [I use to build the CI images](https://gitlab.com/python-devs/ci-images/-/blob/main/get_versions.py#L68) for all active Python versions.

**Comment by ezio-melotti** [comment]
This is discussed in the PR, see:
* https://github.com/endoflife-date/endoflife.date/discussions/711
