### ISSUE TITLE
Document the @proofreaders team

### ISSUE THREAD

**Issue by encukou** [python/devguide#886]
- If you'd like help with English in a Python-related repo (docs, PEPs, devguide, ...), mention @python/proofreaders on GitHub to get their attention
- If you'd like to join *(edited)*: open an issue on [core-workflow](https://github.com/python/core-workflow/issues) similar to [#461 ](https://github.com/python/core-workflow/issues/461).

(I don't know who else has privileges to add members to the team.)

@ezio-melotti, would you like to add this?

**Comment by ezio-melotti** [comment]
We should probably add a section/page to document the existing teams, their purpose, and the process to join them.  This came up in https://github.com/python/core-workflow/issues/458#issuecomment-1148558930 too.

**Comment by CAM-Gerlach** [comment]
I might also suggest refining the team description a touch, perhaps along the lines of "Mention [...] for help with the finer points of English technical writing," to avoid sounding like its just for people who need basic help with English and to reduce any shame someone might feel asking us for help. Indeed, while some may need it more and others less, almost _anyone_'s writing could potentially benefit from a second look by a proofreader—English technical writing may happen to be an area of strength for me, but I certainly still make plenty of mistakes and typos, and could word things more clearly.

**Comment by ezio-melotti** [comment]
FTR there is also a section in the devguide about proofreading that should mention the team: https://devguide.python.org/documentation/help-documenting/#proofreading

**Comment by hugovk** [comment]
Please see PR #1229.

**Comment by hugovk** [comment]
A question from https://github.com/python/devguide/pull/1229#discussion_r1400017282:

> I was also wondering if there are any restrictions for joining the group -- do people that send requests need to be already part of the `python` org (e.g. as triagers)? If so, we should mention that too.

Good question! Are there any restrictions?

I guess some of the people in the team (https://github.com/orgs/python/teams/proofreaders) were added to the org to be able to add them to the team.

I don't think future applicants would need to be already in the org, but we should take care in accepting applications.

**Comment by encukou** [comment]
At the moment, there aren't any restrictions. (Of course, that might change if people start abusing this somehow.)
