### ISSUE TITLE
Git Bootcamp: similar content in two sections

### ISSUE THREAD

**Issue by hugovk** [python/devguide#888]
Two nearby sections have very similar content.

https://devguide.python.org/gitbootcamp/ has a section on "Staging and Committing Files", then after sections on "Reverting Changes" and "Stashing Changes", there's another on "Committing Changes".

* https://devguide.python.org/gitbootcamp/#staging-and-committing-files
* https://devguide.python.org/gitbootcamp/#committing-changes

![image](https://user-images.githubusercontent.com/1324225/172793074-0e7877e1-841b-4a32-a527-237ea1aa4028.png)

Do we need the "Committing Changes" section? It essentially duplicates info already in "Staging and Committing Files".

**Comment by ezio-melotti** [comment]
I think we can remove it.  I would also recommend `git add -p`, which IMHO is easier and less error-prone than a simple `git add`.

**Comment by Darnokiv** [comment]
#902 
Hello there,
I created a draft Pull Request where I deleted the duplicated paragraph and added `git add -p`. Is this so ok?

I'm sorry if something is wrong, that is my first contribution.

**Comment by hugovk** [comment]
Hi there! That looks good, thank you! You can mark it as ready for review :)

**Comment by ezio-melotti** [comment]
The PR is now merged, thanks to @Darnokiv for working on it, @hugovk for the report, and @ambv for fixing the CLA issues!
