### ISSUE TITLE
Make it abundantly clear random people should not ask for commit privileges

### ISSUE THREAD

**Issue by brettcannon** [python/devguide#89]
Twice in the past two weeks people have sent in their SSH keys and GitHub usernames to get commit privileges even though they have never contributed to Python. It seems we need a much louder, explicit message that commit privileges are not for people who are just looking to contribute (maybe #40 would help with this?).

**Comment by berkerpeksag** [comment]
Did they say anything about how they find hgaccounts@p.o? Perhaps we can delete the following paragraph from https://docs.python.org/devguide/coredev.html

> You may request commit privileges yourself, but do not be surprised if your request is turned down. Do not take this personally! It simply means that other core developers think you need more time contributing patches before you are able to commit them without supervision.

**Comment by willingc** [comment]
Strange. I concur with @berkerpeksag that the recommended passage should be deleted.

It would be great to have a direct statement similar to the following added to the READMEs once all repos are on GH and perhaps included message from the bot that asks for new contributors to sign the release:

```
Contributors are welcome and should sign the release. Please do not send SSH keys to the project as they are not needed for you to contribute to the project.

The project grants commit/merge privileges to core developers who have contributed meaningfully over a sustained period of time. We've found that a small number of core developers with commit rights enables the project workflow to be most productive for all contributors.
```

@Mariatta Thoughts on being welcoming yet direct and practical?

**Comment by ncoghlan** [comment]
+1 from me for removing the paragraph @berkerpeksag mentioned (and that can be done without replacing it with anything). The open source dev model already implicitly rewards robust self-confidence, so we really don't need to explicitly encourage that bias :)

In terms of providing a clearer explanation for what it means to become a core committer/reviewer, I'm not sure how to word it concisely, but the key difference for me is in the scope of our responsibilities in different roles:

- as a contributor, our responsibility is to collaborate constructively with other contributors, including core developers.
- as a core developer, our responsibility is to handle the consequences of accepting a change into the code base or documentation. That includes reverting or fixing it if it causes problems in the build bots or someone spots a problem in post-commit review, as well as helping out the release manager resolve any problems found during the pre-release testing cycle.

**Comment by willingc** [comment]
@ncoghlan This is probably the best written distinction that I've seen - both positive and clear.

**Comment by brettcannon** [comment]
OK, paragraph has been deleted in master and github branches. If someone wants to clarify responsibilities as Nick has laid out (although I would add the responsibility of accepting/rejecting contributions on top of the ramifications is part of it), then feel free.

**Comment by willingc** [comment]
Thanks @brettcannon. Happy 2017 :smile:

**Comment by ncoghlan** [comment]
A second attempt at spelling out the additional privileges & responsibilities of core developer status:

> * as contributors, our shared responsibility is to collaborate constructively with other contributors, including core developers.
> * core developers bear the additional responsibility of handling the consequences of accepting a change into the code base or documentation. That includes reverting or fixing it if it causes problems in the buildbot fleet or someone spots a problem in post-commit review, as well as helping out the release manager in resolving any problems found during the pre-release testing cycle. While all contributors are free to help out with this part of the process, and it is most welcome when they do, the actual responsibility rests with the core developer that merged the change.
> * core developers also bear the primary responsibility for deciding when changes proposed on the issue tracker should be escalated to python-ideas or python-dev for wider discussion, as well as suggesting the use of the Python Enhancement Proposal process to manage the design and justifcation of complex changes, or changes with a potentially significant impact to end users.
> * as a result of the additional responsibilities they accept, core developers gain the privilege of being able to approve proposed changes, as well as being able to reject them as inappropriate. Core developers are also able to request that even already merged changes be escalated to python-dev for further discussion, and potentially even reverted prior to release.
>
> Becoming a core developer isn't a binary "all-or-nothing" status - CPython is a large project, and different core developers accept responsibility for making design and development decisions in different areas (as documented in the Experts Index and the Developer Log).

**Comment by ncoghlan** [comment]
I created a PR for a new section that clarifies the additional responsibilities of core developers: https://github.com/python/devguide/pull/95
