### ISSUE TITLE
Windows build instructions out-dated/unclear for 2.7 branch

### ISSUE THREAD

**Issue by yan12125** [python/devguide#90]
Since http://bugs.python.org/issue24508, building 2.7 on Windows is complicated. A typical setup involves Visual Studio 2008 as well as 2010. However, https://github.com/python/devguide/blob/github/setup.rst#windows simply says:

> Most Python versions prior to 3.3 use Microsoft Visual Studio 2008.

Maybe picking some important notes from https://hg.python.org/cpython/file/2.7/PCbuild/readme.txt

**Comment by brettcannon** [comment]
I would also be fine with simplifying the docs to just point people towards the readme.

**Comment by yan12125** [comment]
Thanks @zware! Things are much clearer now!
