### ISSUE TITLE
Mention that dependabot on fork repo should be ignored.

### ISSUE THREAD

**Issue by Mariatta** [python/devguide#980]

**Comment by Mariatta** [comment]
Closing because GitHub fixed this.

**Comment by ezio-melotti** [comment]
See https://github.blog/changelog/2022-11-07-dependabot-pull-requests-off-by-default-for-forks/

**Comment by hugovk** [comment]
Not entirely fixed: existing forks will still get spammed unless each one explicitly disables it in their fork settings:

https://github.com/myusername/cpython/settings/security_analysis

![image](https://user-images.githubusercontent.com/1324225/200519942-1fda7ee5-36a7-47dc-8658-817c564802f2.png)

See https://github.com/dependabot/dependabot-core/issues/2804#issuecomment-1306038858
