### ISSUE TITLE
Check that all symbols in the limited ABI are exported

### ISSUE THREAD

**Issue by pablogsal** [python/devguide#991]
BPO | [42545](https://bugs.python.org/issue42545)
--- | :---
Nosy | @vstinner, @pablogsal, @erlend-aasland
PRs | <li>python/cpython#23616</li><li>python/cpython#23648</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-12-02.20:52:19.505>
labels = ['tests', '3.10']
title = 'Check that all symbols in the limited ABI are exported'
updated_at = <Date 2021-10-27.12:15:50.705>
user = 'https://github.com/pablogsal'
```

bugs.python.org fields:
```python
activity = <Date 2021-10-27.12:15:50.705>
actor = 'pablogsal'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Tests']
creation = <Date 2020-12-02.20:52:19.505>
creator = 'pablogsal'
dependencies = []
files = []
hgrepos = []
issue_num = 42545
keywords = ['patch']
message_count = 7.0
messages = ['382336', '382511', '382536', '382538', '382545', '405074', '405089']
nosy_count = 4.0
nosy_names = ['vstinner', 'Igor.Skochinsky', 'pablogsal', 'erlendaasland']
pr_nums = ['23616', '23648']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue42545'
versions = ['Python 3.10']
```

</p></details>

**Comment by vstinner** [comment]
>iritkatriel transferred this issue from python/cpython Nov 24, 2022 

Hum, for me it's strange that the CPython is "gone" (moved). For next issues, I suggest to create a new issue in the devguide project, rather than transferring issues. Well, that's my opinion. It's not a big deal.

**Comment by pablogsal** [comment]
Apparently this is already in the dev guide:

> https://github.com/python/devguide/blob/7dcba58da8005e87929f8d3397a1f46ed5ade317/developer-workflow/c-api.rst#adding-a-new-definition-to-the-limited-api
